/**
 * 39 new tools extracted from the Ditch That Textbook "50 AI Tools for Teachers" list
 * and the categorized directory screenshot.
 *
 * These will be merged into seed-data.ts
 */

import type { Tool } from "./types";

type PartialTool = Omit<Tool, "id" | "privacy_flag">;

let nextId = 26;
function id() { return String(nextId++); }

export const newTools: PartialTool[] = [
  // ═══════════════════════════════════════════
  // CHATBOTS & GENERAL AI
  // ═══════════════════════════════════════════
  {
    slug: "microsoft-copilot", name: "Microsoft Copilot", vendor: "Microsoft",
    website: "https://copilot.microsoft.com", affiliate_url: "https://copilot.microsoft.com?ref=dai",
    logo_url: "/logos/mscopilot.svg",
    description: "Microsoft's AI assistant integrated across Microsoft 365 Education with enterprise-grade security and admin controls.",
    overview: "Microsoft Copilot brings AI into Word, PowerPoint, Teams, and Excel with data protection built for education. Admin controls allow age-gating and feature management through the Microsoft 365 admin center.",
    why_it_matters: "Seamless AI for Microsoft 365 schools with enterprise-grade compliance.",
    best_for: ["Microsoft 365 integration", "Document creation", "Data analysis", "Meeting summaries"],
    not_ideal_for: ["Non-Microsoft environments", "Specialized lesson planning", "Young learners"],
    key_features: ["Integrated in M365 apps", "Document drafting", "Presentation creation", "Data analysis", "Meeting summaries in Teams"],
    instructional_fit: "Seamless for Microsoft-heavy districts. Enhances existing workflows.",
    implementation_notes: "Available through Microsoft 365 Education A3/A5. Enabled through admin center.",
    privacy_notes: "Enterprise-grade security. FERPA compliant under Microsoft education agreement. Data not used for model training.",
    accessibility_notes: "Strong. Inherits Microsoft 365 accessibility features including screen reader support.",
    admin_integration_notes: "Full admin control through Microsoft 365 admin center. Granular AI feature control.",
    editorial_verdict: "The strategic choice for Microsoft 365 Education districts. Excellent admin controls and enterprise security.",
    categories: ["General AI"], grade_bands: ["6-8", "9-12"], audiences: ["Teachers", "Students", "Administrators"],
    pricing_type: "Paid", pricing_details: "Included with Microsoft 365 Education A3/A5 plans.",
    privacy_level: "High", accessibility_level: "Strong",
    scores: { ease_of_use: 8, instructional_value: 8, data_privacy: 9, accessibility: 9 }, overall_score: 8.4,
    tags: ["Microsoft", "productivity", "enterprise", "integration"],
    integrations: ["Microsoft Teams", "Word", "PowerPoint", "Excel", "OneNote"],
    compliance_signals: [
      { label: "FERPA Compliant", status: "available", url: "https://learn.microsoft.com/en-us/compliance/regulatory/offering-ferpa" },
      { label: "COPPA Compliant", status: "available", url: "https://learn.microsoft.com/en-us/compliance/regulatory/offering-ferpa" },
      { label: "SOC 2 Type II", status: "available", url: "https://www.microsoft.com/en-us/trust-center/compliance/accessibility" },
      { label: "DPA Available", status: "available", url: "https://learn.microsoft.com/en-us/copilot/microsoft-365/microsoft-365-copilot-privacy" },
      { label: "VPAT/ACR", status: "available", url: "https://www.microsoft.com/en-us/accessibility/conformance-reports" },
    ],
    vpat_status: "available", vpat_url: "https://www.microsoft.com/en-us/accessibility/conformance-reports", vpat_notes: "Microsoft publishes comprehensive ACRs for all products.",
    last_reviewed: "2026-03-28", reviewer_notes: "Enterprise-grade AI for Microsoft districts.",
    listing_tier: "featured", is_featured: false, featured_rank: null, is_sponsored: false, status: "published",
    similar_tools: ["gemini", "chatgpt"],
  },
  {
    slug: "claude", name: "Claude", vendor: "Anthropic",
    website: "https://claude.ai", affiliate_url: "https://claude.ai?ref=dai",
    logo_url: "/logos/claude.svg",
    description: "Anthropic's safety-focused AI assistant with nuanced reasoning, strong content moderation, and a learning mode for education.",
    overview: "Claude is designed with safety-first principles. Its learning mode encourages student thinking rather than providing direct answers. Enterprise plans offer data isolation and SOC 2 compliance.",
    why_it_matters: "Most safety-conscious general AI with a dedicated education learning mode.",
    best_for: ["Safe AI interaction", "Critical thinking", "Writing feedback", "Research assistance"],
    not_ideal_for: ["Interactive classroom activities", "Flashcards", "Visual content creation"],
    key_features: ["Learning mode", "Strong content moderation", "Nuanced reasoning", "Long document analysis", "System prompts"],
    instructional_fit: "Excellent for higher-order thinking. Learning mode helps students engage with problems rather than receiving answers.",
    implementation_notes: "Available through web and API. Education-specific plans in development.",
    privacy_notes: "Strong privacy commitments. Enterprise plans offer data isolation. SOC 2 Type II certified.",
    accessibility_notes: "Web interface supports standard accessibility. Keyboard navigable.",
    admin_integration_notes: "Enterprise admin console. Usage monitoring. Custom system prompts.",
    editorial_verdict: "The most safety-conscious AI assistant available. Learning mode is uniquely valuable for education.",
    categories: ["General AI"], grade_bands: ["6-8", "9-12"], audiences: ["Teachers", "Students", "Administrators"],
    pricing_type: "Freemium", pricing_details: "Free tier. Pro at $20/mo. Education plans available.",
    privacy_level: "High", accessibility_level: "Moderate",
    scores: { ease_of_use: 8, instructional_value: 9, data_privacy: 9, accessibility: 7 }, overall_score: 8.5,
    tags: ["AI assistant", "safety-first", "reasoning", "writing", "research"],
    integrations: ["API"],
    compliance_signals: [
      { label: "FERPA Compliant", status: "partial", url: "https://trust.anthropic.com/" },
      { label: "SOC 2 Type II", status: "available", url: "https://trust.anthropic.com/" },
      { label: "DPA Available", status: "available", url: "https://privacy.anthropic.com/" },
    ],
    vpat_status: "not_available", vpat_url: null, vpat_notes: "No public VPAT/ACR found. Contact vendor.",
    last_reviewed: "2026-03-30", reviewer_notes: "Top marks for safety. Education plans maturing.",
    listing_tier: "featured", is_featured: true, featured_rank: 8, is_sponsored: false, status: "published",
    similar_tools: ["chatgpt", "gemini", "microsoft-copilot"],
  },
  {
    slug: "perplexity", name: "Perplexity", vendor: "Perplexity AI",
    website: "https://perplexity.ai", affiliate_url: "https://perplexity.ai?ref=dai",
    logo_url: "/logos/perplexity.svg",
    description: "AI-powered research assistant that provides source-cited answers — valuable for teaching information literacy and research skills.",
    overview: "Perplexity provides answers with cited sources, making it more reliable than generic chatbots for research. Best for secondary students and teachers doing research-based learning.",
    why_it_matters: "Source-cited AI research — teaches information literacy by default.",
    best_for: ["Research projects", "Source-based learning", "Fact-checking", "Current events"],
    not_ideal_for: ["Young students", "Creative writing", "District-managed deployment"],
    key_features: ["Source-cited answers", "Follow-up questions", "Academic source focus", "Collections"],
    instructional_fit: "Valuable for teaching research skills and source evaluation. Citation-first approach supports information literacy.",
    implementation_notes: "Free web tool. No formal education deployment.",
    privacy_notes: "Not specifically designed for K–12. Free/Pro plans may use data for training (opt-out available). No formal FERPA commitment.",
    accessibility_notes: "Clean, readable interface. Standard web accessibility.",
    admin_integration_notes: "No admin controls. Individual use only.",
    editorial_verdict: "Excellent research tool with strong citation practices, but lacks formal K–12 compliance. Best for teacher use and supervised secondary research.",
    categories: ["General AI"], grade_bands: ["9-12"], audiences: ["Teachers", "Students"],
    pricing_type: "Freemium", pricing_details: "Free tier. Pro at $20/mo. No education pricing.",
    privacy_level: "Medium", accessibility_level: "Moderate",
    scores: { ease_of_use: 8, instructional_value: 8, data_privacy: 5, accessibility: 7 }, overall_score: 7.3,
    tags: ["research", "citations", "search", "fact-checking"],
    integrations: [],
    compliance_signals: [
      { label: "FERPA Compliant", status: "unknown", url: null },
      { label: "COPPA Compliant", status: "unavailable", url: null },
    ],
    vpat_status: "not_available", vpat_url: null, vpat_notes: "No public VPAT. Not education-specific.",
    last_reviewed: "2026-03-25", reviewer_notes: "Powerful for research but needs formal education compliance.",
    listing_tier: "basic", is_featured: false, featured_rank: null, is_sponsored: false, status: "published",
    similar_tools: ["google-notebooklm", "chatgpt"],
  },
  {
    slug: "pi", name: "Pi", vendor: "Inflection AI",
    website: "https://pi.ai", affiliate_url: "https://pi.ai?ref=dai",
    logo_url: "/logos/pi.svg",
    description: "Conversational AI designed to be empathetic and supportive — a gentler alternative to ChatGPT for student-facing use.",
    overview: "Pi is built to be kind, curious, and helpful. Its empathetic conversational style makes it potentially suitable for student social-emotional support, though it lacks formal education compliance.",
    why_it_matters: "Empathetic AI conversation partner — gentler than ChatGPT for students.",
    best_for: ["Supportive conversation", "Brainstorming", "Writing help", "Social-emotional learning"],
    not_ideal_for: ["Assessment", "Lesson planning", "District deployment", "Data analysis"],
    key_features: ["Empathetic conversation", "Voice mode", "Personalized responses"],
    instructional_fit: "Unique empathetic approach could support SEL. Not designed for academic instruction.",
    implementation_notes: "Free web and mobile app. No education-specific features.",
    privacy_notes: "No formal education compliance. General consumer privacy policy.",
    accessibility_notes: "Mobile-friendly. Voice input available.",
    admin_integration_notes: "No admin controls. Individual use only.",
    editorial_verdict: "An interesting conversational AI with a uniquely empathetic tone, but no education-specific compliance or features.",
    categories: ["General AI"], grade_bands: ["9-12"], audiences: ["Teachers"],
    pricing_type: "Free", pricing_details: "Free to use.",
    privacy_level: "Medium", accessibility_level: "Moderate",
    scores: { ease_of_use: 9, instructional_value: 6, data_privacy: 5, accessibility: 7 }, overall_score: 6.6,
    tags: ["chatbot", "empathetic", "conversational", "SEL"],
    integrations: [],
    compliance_signals: [{ label: "FERPA Compliant", status: "unknown", url: null }],
    vpat_status: "not_available", vpat_url: null, vpat_notes: "No public VPAT. Not education-specific.",
    last_reviewed: "2026-03-20", reviewer_notes: "Interesting tone but not built for schools.",
    listing_tier: "basic", is_featured: false, featured_rank: null, is_sponsored: false, status: "published",
    similar_tools: ["chatgpt", "claude"],
  },
  {
    slug: "hello-history", name: "Hello History", vendor: "Hello History",
    website: "https://www.hellohistory.ai", affiliate_url: "https://www.hellohistory.ai?ref=dai",
    logo_url: "/logos/hellohistory.svg",
    description: "AI-powered conversations with historical figures — students can chat with Einstein, Cleopatra, or MLK for immersive history learning.",
    overview: "Hello History uses AI to simulate conversations with historical figures. Students ask questions and receive responses written in the voice and perspective of the historical figure.",
    why_it_matters: "Immersive history learning through AI-simulated conversations with historical figures.",
    best_for: ["History instruction", "Primary source engagement", "Student engagement", "Critical thinking"],
    not_ideal_for: ["Math/science", "Assessment", "Administrative tasks"],
    key_features: ["Historical figure conversations", "Multiple time periods", "Educational context"],
    instructional_fit: "Engaging for history and social studies. Teachers should frame as 'AI interpretation' not factual primary source.",
    implementation_notes: "Mobile app. No school deployment features.",
    privacy_notes: "Limited education-specific privacy documentation.",
    accessibility_notes: "Mobile app with standard accessibility.",
    admin_integration_notes: "No admin features.",
    editorial_verdict: "A creative engagement tool for history classes, but limited scope and no formal compliance documentation.",
    categories: ["Student Support"], grade_bands: ["6-8", "9-12"], audiences: ["Teachers", "Students"],
    pricing_type: "Freemium", pricing_details: "Free tier with limited conversations. Premium available.",
    privacy_level: "Medium", accessibility_level: "Moderate",
    scores: { ease_of_use: 8, instructional_value: 7, data_privacy: 5, accessibility: 6 }, overall_score: 6.7,
    tags: ["history", "engagement", "simulation", "conversation"],
    integrations: [],
    compliance_signals: [{ label: "FERPA Compliant", status: "unknown", url: null }],
    vpat_status: "not_available", vpat_url: null, vpat_notes: "No VPAT. Small vendor.",
    last_reviewed: "2026-03-15", reviewer_notes: "Creative but niche. No compliance docs.",
    listing_tier: "basic", is_featured: false, featured_rank: null, is_sponsored: false, status: "published",
    similar_tools: [],
  },
  {
    slug: "antimatter-sorcerer", name: "Antimatter Sorcerer", vendor: "Antimatter",
    website: "https://antimatter.systems", affiliate_url: "https://antimatter.systems?ref=dai",
    logo_url: "/logos/antimatter.svg",
    description: "AI chatbot designed specifically for education with built-in content filters and student safety guardrails.",
    overview: "Antimatter Sorcerer provides a student-safe AI chat experience with content filtering designed for K–12 classrooms.",
    why_it_matters: "Education-first chatbot with built-in safety for student use.",
    best_for: ["Safe student AI chat", "Research assistance", "Writing help"],
    not_ideal_for: ["Lesson planning", "Assessment", "Admin tasks"],
    key_features: ["Content filtering", "Education-focused responses", "Student safety guardrails"],
    instructional_fit: "Designed for safe student interaction with AI.",
    implementation_notes: "Web-based. Check vendor for school deployment options.",
    privacy_notes: "Education-focused. Check vendor for current compliance status.",
    accessibility_notes: "Web-based with standard accessibility.",
    admin_integration_notes: "Limited admin features.",
    editorial_verdict: "An education-focused chatbot alternative worth monitoring as it develops.",
    categories: ["General AI"], grade_bands: ["6-8", "9-12"], audiences: ["Teachers", "Students"],
    pricing_type: "Freemium", pricing_details: "Free tier available.",
    privacy_level: "Medium", accessibility_level: "Moderate",
    scores: { ease_of_use: 7, instructional_value: 7, data_privacy: 6, accessibility: 7 }, overall_score: 6.9,
    tags: ["chatbot", "student-safe", "education"],
    integrations: [],
    compliance_signals: [{ label: "FERPA Compliant", status: "unknown", url: null }],
    vpat_status: "not_available", vpat_url: null, vpat_notes: "No public VPAT found.",
    last_reviewed: "2026-03-18", reviewer_notes: "Early-stage education chatbot.",
    listing_tier: "basic", is_featured: false, featured_rank: null, is_sponsored: false, status: "published",
    similar_tools: ["schoolai", "claude"],
  },

  // ═══════════════════════════════════════════
  // VISUAL & DESIGN TOOLS
  // ═══════════════════════════════════════════
  {
    slug: "microsoft-designer", name: "Microsoft Designer", vendor: "Microsoft",
    website: "https://designer.microsoft.com", affiliate_url: "https://designer.microsoft.com?ref=dai",
    logo_url: "/logos/msdesigner.svg",
    description: "Microsoft's AI-powered design tool for creating social media graphics, invitations, and visual content — free with Microsoft account.",
    overview: "Microsoft Designer uses AI to generate and edit images, create designs from text prompts, and produce social media-ready content.",
    why_it_matters: "Free AI design tool with Microsoft's enterprise security for schools.",
    best_for: ["Visual content creation", "Social media graphics", "Quick design projects"],
    not_ideal_for: ["Lesson planning", "Assessment", "Complex design work"],
    key_features: ["AI image generation", "Template library", "Text-to-design", "Brand kit"],
    instructional_fit: "Good for student creative projects and teacher materials.",
    implementation_notes: "Free with Microsoft account. No special deployment needed.",
    privacy_notes: "Microsoft privacy standards apply. Enterprise-grade for education accounts.",
    accessibility_notes: "Strong. Microsoft accessibility standards.",
    admin_integration_notes: "Managed through Microsoft 365 admin center.",
    editorial_verdict: "A solid free design tool for Microsoft-ecosystem schools.",
    categories: ["Content Creation"], grade_bands: ["3-5", "6-8", "9-12"], audiences: ["Teachers", "Students"],
    pricing_type: "Free", pricing_details: "Free with Microsoft account.",
    privacy_level: "High", accessibility_level: "Strong",
    scores: { ease_of_use: 8, instructional_value: 7, data_privacy: 9, accessibility: 8 }, overall_score: 7.9,
    tags: ["design", "AI images", "Microsoft", "creative"],
    integrations: ["Microsoft 365"],
    compliance_signals: [
      { label: "FERPA Compliant", status: "available", url: "https://learn.microsoft.com/en-us/compliance/regulatory/offering-ferpa" },
      { label: "COPPA Compliant", status: "available", url: "https://learn.microsoft.com/en-us/compliance/regulatory/offering-ferpa" },
      { label: "VPAT/ACR", status: "available", url: "https://www.microsoft.com/en-us/accessibility/conformance-reports" },
    ],
    vpat_status: "available", vpat_url: "https://www.microsoft.com/en-us/accessibility/conformance-reports", vpat_notes: "Covered by Microsoft's comprehensive ACR program.",
    last_reviewed: "2026-03-22", reviewer_notes: "Solid free option for Microsoft schools.",
    listing_tier: "basic", is_featured: false, featured_rank: null, is_sponsored: false, status: "published",
    similar_tools: ["canva", "adobe-express"],
  },
  {
    slug: "ideogram", name: "Ideogram", vendor: "Ideogram Inc.",
    website: "https://ideogram.ai", affiliate_url: "https://ideogram.ai?ref=dai",
    logo_url: "/logos/ideogram.svg",
    description: "AI image generation tool that excels at text-in-images — useful for creating posters, infographics, and visual materials with readable text.",
    overview: "Ideogram generates AI images with unusually accurate text rendering, making it useful for educational posters, diagrams, and visual aids.",
    why_it_matters: "Best AI image generator for text-heavy visuals like posters and infographics.",
    best_for: ["Poster creation", "Infographics with text", "Visual aids", "Creative projects"],
    not_ideal_for: ["Lesson planning", "Assessment", "Student-facing use without supervision"],
    key_features: ["Text-in-image generation", "Multiple styles", "High resolution output"],
    instructional_fit: "Useful for teacher-created visual materials. Requires supervision for student use.",
    implementation_notes: "Web-based. Individual accounts. No education deployment.",
    privacy_notes: "General consumer platform. Not education-specific.",
    accessibility_notes: "Web interface with basic accessibility.",
    admin_integration_notes: "No admin features.",
    editorial_verdict: "Best-in-class for AI images with text. Useful for creating classroom visuals but not education-specific.",
    categories: ["Content Creation"], grade_bands: ["6-8", "9-12"], audiences: ["Teachers"],
    pricing_type: "Freemium", pricing_details: "Free tier with daily limits. Pro plans available.",
    privacy_level: "Medium", accessibility_level: "Moderate",
    scores: { ease_of_use: 8, instructional_value: 7, data_privacy: 5, accessibility: 6 }, overall_score: 6.8,
    tags: ["AI images", "design", "posters", "infographics"],
    integrations: [],
    compliance_signals: [{ label: "FERPA Compliant", status: "unknown", url: null }],
    vpat_status: "not_available", vpat_url: null, vpat_notes: "No VPAT. Not education-specific.",
    last_reviewed: "2026-03-10", reviewer_notes: "Great for visuals, not built for schools.",
    listing_tier: "basic", is_featured: false, featured_rank: null, is_sponsored: false, status: "published",
    similar_tools: ["canva", "microsoft-designer"],
  },
  {
    slug: "autodraw", name: "AutoDraw", vendor: "Google",
    website: "https://autodraw.com", affiliate_url: "https://autodraw.com?ref=dai",
    logo_url: "/logos/autodraw.svg",
    description: "Google's free AI drawing tool that turns rough sketches into polished clip art — great for quick visual content.",
    overview: "AutoDraw uses AI to suggest professional drawings from rough sketches. Simple enough for any age level and completely free.",
    why_it_matters: "Turns anyone's rough sketches into clean drawings — free from Google.",
    best_for: ["Quick illustrations", "Visual aids", "Student art projects", "Accessible drawing"],
    not_ideal_for: ["Complex design", "Photo editing", "Lesson planning"],
    key_features: ["AI sketch recognition", "Clip art suggestions", "Simple drawing tools", "Download as PNG"],
    instructional_fit: "Great for quick visual aids. Accessible to all ages and skill levels.",
    implementation_notes: "Free web tool. No account required. No deployment needed.",
    privacy_notes: "Google product. Minimal data collection — no account required.",
    accessibility_notes: "Simple web interface. Touch-friendly.",
    admin_integration_notes: "No admin needed. Free, open tool.",
    editorial_verdict: "A charming, simple tool that's perfect for quick classroom visuals. Zero friction.",
    categories: ["Content Creation"], grade_bands: ["K-2", "3-5", "6-8", "9-12"], audiences: ["Teachers", "Students"],
    pricing_type: "Free", pricing_details: "Completely free. No premium tier.",
    privacy_level: "High", accessibility_level: "Strong",
    scores: { ease_of_use: 10, instructional_value: 6, data_privacy: 8, accessibility: 8 }, overall_score: 7.6,
    tags: ["drawing", "sketching", "Google", "free", "visual"],
    integrations: [],
    compliance_signals: [
      { label: "FERPA Compliant", status: "available", url: "https://edu.google.com/intl/ALL_us/our-values/privacy-security/" },
    ],
    vpat_status: "on_request", vpat_url: "https://belonging.google/accessibility-conformance-reports/", vpat_notes: "Google product. Check Google ACR hub.",
    last_reviewed: "2026-02-15", reviewer_notes: "Simple and delightful. Perfect for elementary.",
    listing_tier: "basic", is_featured: false, featured_rank: null, is_sponsored: false, status: "published",
    similar_tools: ["canva", "microsoft-designer"],
  },
  {
    slug: "google-vids", name: "Google Vids", vendor: "Google",
    website: "https://workspace.google.com/products/vids", affiliate_url: "https://workspace.google.com/products/vids?ref=dai",
    logo_url: "/logos/googlevids.svg",
    description: "Google's AI-powered video creation tool built into Workspace — create polished videos from text and slides.",
    overview: "Google Vids uses AI to help create video presentations and explainer videos within the Google Workspace ecosystem.",
    why_it_matters: "AI video creation native to Google Workspace for schools.",
    best_for: ["Video presentations", "Explainer videos", "Student projects", "Teacher materials"],
    not_ideal_for: ["Live instruction", "Assessment", "Complex video editing"],
    key_features: ["Text-to-video", "Slide-to-video", "AI narration", "Google Workspace integration"],
    instructional_fit: "Natural extension of Google Slides for video content creation.",
    implementation_notes: "Available through Google Workspace for Education Plus.",
    privacy_notes: "Inherits Google Workspace for Education privacy protections.",
    accessibility_notes: "Google accessibility standards. Auto-captions.",
    admin_integration_notes: "Google Admin Console management.",
    editorial_verdict: "A natural addition for Google Workspace schools needing AI video creation.",
    categories: ["Content Creation"], grade_bands: ["3-5", "6-8", "9-12"], audiences: ["Teachers", "Students"],
    pricing_type: "Paid", pricing_details: "Included with Google Workspace for Education Plus.",
    privacy_level: "High", accessibility_level: "Strong",
    scores: { ease_of_use: 8, instructional_value: 7, data_privacy: 9, accessibility: 8 }, overall_score: 7.9,
    tags: ["video", "Google", "workspace", "presentations"],
    integrations: ["Google Workspace", "Google Slides", "Google Drive"],
    compliance_signals: [
      { label: "FERPA Compliant", status: "available", url: "https://edu.google.com/intl/ALL_us/our-values/privacy-security/" },
      { label: "COPPA Compliant", status: "available", url: "https://edu.google.com/intl/ALL_us/our-values/privacy-security/" },
    ],
    vpat_status: "on_request", vpat_url: "https://belonging.google/accessibility-conformance-reports/", vpat_notes: "Google product. Check ACR hub.",
    last_reviewed: "2026-03-20", reviewer_notes: "New Google product. Strong potential for Workspace schools.",
    listing_tier: "basic", is_featured: false, featured_rank: null, is_sponsored: false, status: "published",
    similar_tools: ["lumen5", "pictory"],
  },
  {
    slug: "prezi-ai", name: "Prezi AI", vendor: "Prezi",
    website: "https://prezi.com", affiliate_url: "https://prezi.com?ref=dai",
    logo_url: "/logos/prezi.svg",
    description: "AI-enhanced presentation platform with zooming canvas and non-linear storytelling — now with AI content generation.",
    overview: "Prezi's unique zooming presentation style now includes AI features for content generation, slide design, and presentation coaching.",
    why_it_matters: "Non-linear presentations with AI content generation for engaging storytelling.",
    best_for: ["Non-linear presentations", "Visual storytelling", "Student projects", "Teacher demos"],
    not_ideal_for: ["Assessment", "Lesson planning", "Data analysis"],
    key_features: ["Zooming canvas", "AI content generation", "Presentation templates", "Video presentations"],
    instructional_fit: "Supports visual and spatial learners with non-linear presentation style.",
    implementation_notes: "Web-based. Education plans available.",
    privacy_notes: "Education accounts with privacy protections. Check vendor for current compliance.",
    accessibility_notes: "Moderate. Non-linear presentations can challenge screen readers.",
    admin_integration_notes: "Education admin dashboard available.",
    editorial_verdict: "A creative alternative to linear slide decks with useful AI features.",
    categories: ["Content Creation"], grade_bands: ["6-8", "9-12"], audiences: ["Teachers", "Students"],
    pricing_type: "Freemium", pricing_details: "Free basic. Education plans available.",
    privacy_level: "Medium", accessibility_level: "Moderate",
    scores: { ease_of_use: 7, instructional_value: 7, data_privacy: 7, accessibility: 6 }, overall_score: 6.9,
    tags: ["presentations", "visual", "storytelling", "creative"],
    integrations: ["Google Classroom"],
    compliance_signals: [{ label: "FERPA Compliant", status: "partial", url: null }],
    vpat_status: "not_available", vpat_url: null, vpat_notes: "No public VPAT found.",
    last_reviewed: "2026-03-12", reviewer_notes: "Creative tool. Accessibility is a concern.",
    listing_tier: "basic", is_featured: false, featured_rank: null, is_sponsored: false, status: "published",
    similar_tools: ["canva", "gamma"],
  },
  {
    slug: "gamma", name: "Gamma", vendor: "Gamma Tech Inc.",
    website: "https://gamma.app", affiliate_url: "https://gamma.app?ref=dai",
    logo_url: "/logos/gamma.svg",
    description: "AI-powered presentation and document creator that generates polished decks from text prompts in seconds.",
    overview: "Gamma uses AI to create presentations, documents, and web pages from text descriptions. Teachers can quickly generate professional-looking materials.",
    why_it_matters: "Fastest way to create polished presentations from a text prompt.",
    best_for: ["Quick presentations", "Document creation", "Web pages", "Student projects"],
    not_ideal_for: ["Complex lesson design", "Assessment", "Data analysis"],
    key_features: ["Text-to-presentation", "AI design", "Embeddable content", "Collaboration"],
    instructional_fit: "Good for rapid content creation. Output needs teacher review.",
    implementation_notes: "Web-based. Google/email sign-in. Check district policy on third-party logins.",
    privacy_notes: "General platform. Not education-specific. Review privacy policy for FERPA/COPPA considerations.",
    accessibility_notes: "Web-accessible. Generated content may need accessibility adjustments.",
    admin_integration_notes: "No education admin features.",
    editorial_verdict: "Fast and impressive for quick presentations, but not education-specific. Teacher supervision recommended.",
    categories: ["Content Creation"], grade_bands: ["6-8", "9-12"], audiences: ["Teachers", "Students"],
    pricing_type: "Freemium", pricing_details: "Free tier with credits. Pro plans available.",
    privacy_level: "Medium", accessibility_level: "Moderate",
    scores: { ease_of_use: 9, instructional_value: 7, data_privacy: 5, accessibility: 6 }, overall_score: 7.0,
    tags: ["presentations", "AI design", "documents", "web pages"],
    integrations: [],
    compliance_signals: [{ label: "FERPA Compliant", status: "unknown", url: null }],
    vpat_status: "not_available", vpat_url: null, vpat_notes: "No VPAT. Not education-specific.",
    last_reviewed: "2026-03-08", reviewer_notes: "Impressive output. No compliance docs.",
    listing_tier: "basic", is_featured: false, featured_rank: null, is_sponsored: false, status: "published",
    similar_tools: ["slidesai", "prezi-ai", "canva"],
  },
  {
    slug: "visme", name: "Visme", vendor: "Visme",
    website: "https://visme.co", affiliate_url: "https://visme.co?ref=dai",
    logo_url: "/logos/visme.svg",
    description: "AI-powered visual content platform for infographics, presentations, and data visualization — strong education offering.",
    overview: "Visme provides AI-powered design tools for creating infographics, presentations, reports, and interactive content with education-specific templates.",
    why_it_matters: "Best-in-class infographic and data visualization tool for education.",
    best_for: ["Infographics", "Data visualization", "Interactive presentations", "Student portfolios"],
    not_ideal_for: ["Lesson planning", "Assessment", "AI tutoring"],
    key_features: ["AI design assistant", "Infographic templates", "Data visualization", "Interactive content", "Education templates"],
    instructional_fit: "Excellent for visual learning and data literacy projects.",
    implementation_notes: "Web-based. Education plans with classroom management.",
    privacy_notes: "Education plans available with privacy protections.",
    accessibility_notes: "Web-accessible. Keyboard navigation supported.",
    admin_integration_notes: "Education admin features for classroom management.",
    editorial_verdict: "A strong visual content platform with genuine education features. Good for data literacy.",
    categories: ["Content Creation"], grade_bands: ["6-8", "9-12"], audiences: ["Teachers", "Students"],
    pricing_type: "Freemium", pricing_details: "Free basic. Education plans available.",
    privacy_level: "Medium", accessibility_level: "Moderate",
    scores: { ease_of_use: 7, instructional_value: 8, data_privacy: 6, accessibility: 7 }, overall_score: 7.2,
    tags: ["infographics", "data visualization", "design", "visual"],
    integrations: ["Google Classroom"],
    compliance_signals: [{ label: "FERPA Compliant", status: "partial", url: null }],
    vpat_status: "not_available", vpat_url: null, vpat_notes: "No public VPAT found.",
    last_reviewed: "2026-03-05", reviewer_notes: "Strong for visual content. Education features growing.",
    listing_tier: "basic", is_featured: false, featured_rank: null, is_sponsored: false, status: "published",
    similar_tools: ["canva", "gamma"],
  },
  {
    slug: "beautiful-ai", name: "Beautiful.ai", vendor: "Beautiful.ai",
    website: "https://beautiful.ai", affiliate_url: "https://beautiful.ai?ref=dai",
    logo_url: "/logos/beautifulai.svg",
    description: "AI presentation tool that automatically applies professional design rules — slides look polished without design skills.",
    overview: "Beautiful.ai uses AI to enforce good design principles automatically. As you add content, the AI adjusts layout, spacing, and visual hierarchy.",
    why_it_matters: "Auto-designs professional slides — no design skills needed.",
    best_for: ["Professional presentations", "Teacher materials", "Student projects"],
    not_ideal_for: ["Assessment", "Lesson planning", "Highly custom designs"],
    key_features: ["AI-powered design rules", "Smart templates", "Team collaboration", "Export options"],
    instructional_fit: "Good for creating professional-looking materials quickly.",
    implementation_notes: "Web-based. Team plans available.",
    privacy_notes: "General platform. Not education-specific.",
    accessibility_notes: "Modern web interface.",
    admin_integration_notes: "Team admin features available.",
    editorial_verdict: "Impressive auto-design capabilities but not education-specific.",
    categories: ["Content Creation"], grade_bands: ["9-12"], audiences: ["Teachers"],
    pricing_type: "Paid", pricing_details: "Pro at $12/mo. Team plans available.",
    privacy_level: "Medium", accessibility_level: "Moderate",
    scores: { ease_of_use: 8, instructional_value: 6, data_privacy: 6, accessibility: 7 }, overall_score: 6.7,
    tags: ["presentations", "design", "AI layout"],
    integrations: [],
    compliance_signals: [],
    vpat_status: "not_available", vpat_url: null, vpat_notes: "No VPAT. Not education-specific.",
    last_reviewed: "2026-02-20", reviewer_notes: "Nice design tool. Not built for schools.",
    listing_tier: "basic", is_featured: false, featured_rank: null, is_sponsored: false, status: "published",
    similar_tools: ["gamma", "prezi-ai"],
  },

  // ═══════════════════════════════════════════
  // LESSON DESIGN & CONTENT CREATION
  // ═══════════════════════════════════════════
  {
    slug: "wewillwrite", name: "WeWillWrite", vendor: "WeWillWrite",
    website: "https://wewillwrite.com", affiliate_url: "https://wewillwrite.com?ref=dai",
    logo_url: "/logos/wewillwrite.svg",
    description: "AI writing assistant designed for classroom writing instruction — helps students develop writing skills with structured feedback.",
    overview: "WeWillWrite provides AI-powered writing support specifically designed for K–12 classrooms with teacher oversight.",
    why_it_matters: "Writing instruction AI designed specifically for classroom use.",
    best_for: ["Writing instruction", "Structured feedback", "Essay development"],
    not_ideal_for: ["Math", "Assessment generation", "Admin tasks"],
    key_features: ["Writing feedback", "Structured prompts", "Teacher dashboard", "Writing process support"],
    instructional_fit: "Designed for writing instruction workflows.",
    implementation_notes: "Web-based. School plans available.",
    privacy_notes: "Education-focused. Check vendor for current compliance documentation.",
    accessibility_notes: "Web-accessible.",
    admin_integration_notes: "Teacher dashboard for student progress.",
    editorial_verdict: "A focused writing instruction tool worth evaluating for ELA departments.",
    categories: ["Writing Support"], grade_bands: ["3-5", "6-8", "9-12"], audiences: ["Teachers", "Students"],
    pricing_type: "Freemium", pricing_details: "Free tier. School plans available.",
    privacy_level: "Medium", accessibility_level: "Moderate",
    scores: { ease_of_use: 7, instructional_value: 8, data_privacy: 6, accessibility: 7 }, overall_score: 7.2,
    tags: ["writing", "ELA", "feedback", "instruction"],
    integrations: ["Google Classroom"],
    compliance_signals: [{ label: "FERPA Compliant", status: "partial", url: null }],
    vpat_status: "not_available", vpat_url: null, vpat_notes: "No public VPAT found.",
    last_reviewed: "2026-03-01", reviewer_notes: "Promising ELA tool.",
    listing_tier: "basic", is_featured: false, featured_rank: null, is_sponsored: false, status: "published",
    similar_tools: ["grammarly", "quillbot"],
  },
  {
    slug: "groovelit", name: "Groovelit", vendor: "Groovelit",
    website: "https://groovelit.com", affiliate_url: "https://groovelit.com?ref=dai",
    logo_url: "/logos/groovelit.svg",
    description: "AI-powered lesson content creation tool that generates standards-aligned materials from teacher input.",
    overview: "Groovelit helps teachers create lesson content, activities, and resources aligned to standards using AI.",
    why_it_matters: "Standards-aligned content generation for lesson design.",
    best_for: ["Lesson content creation", "Standards alignment", "Activity generation"],
    not_ideal_for: ["Student-facing AI", "Assessment grading", "Admin tasks"],
    key_features: ["Standards-aligned content", "Activity generator", "Multiple content types"],
    instructional_fit: "Supports backward design and standards-based planning.",
    implementation_notes: "Web-based. Individual teacher accounts.",
    privacy_notes: "Teacher-facing tool. Minimal student data collection.",
    accessibility_notes: "Web-accessible.",
    admin_integration_notes: "Individual tool.",
    editorial_verdict: "A useful content generation tool for standards-based lesson planning.",
    categories: ["Lesson Planning"], grade_bands: ["K-2", "3-5", "6-8", "9-12"], audiences: ["Teachers"],
    pricing_type: "Freemium", pricing_details: "Free tier available.",
    privacy_level: "Medium", accessibility_level: "Moderate",
    scores: { ease_of_use: 7, instructional_value: 8, data_privacy: 7, accessibility: 7 }, overall_score: 7.4,
    tags: ["lesson planning", "standards", "content creation"],
    integrations: [],
    compliance_signals: [{ label: "FERPA Compliant", status: "partial", url: null }],
    vpat_status: "not_available", vpat_url: null, vpat_notes: "No public VPAT found.",
    last_reviewed: "2026-02-28", reviewer_notes: "Solid lesson content tool.",
    listing_tier: "basic", is_featured: false, featured_rank: null, is_sponsored: false, status: "published",
    similar_tools: ["magicschool-ai", "eduaide-ai"],
  },
  {
    slug: "teachaid", name: "TeachAid", vendor: "TeachAid",
    website: "https://teachaid.co", affiliate_url: "https://teachaid.co?ref=dai",
    logo_url: "/logos/teachaid.svg",
    description: "AI teaching assistant that helps teachers create lesson plans, worksheets, and educational resources quickly.",
    overview: "TeachAid uses AI to generate lesson plans, worksheets, rubrics, and other teaching materials from simple prompts.",
    why_it_matters: "Quick AI-generated teaching materials from simple prompts.",
    best_for: ["Lesson planning", "Worksheet creation", "Rubric generation"],
    not_ideal_for: ["Student-facing AI", "Interactive activities", "Video content"],
    key_features: ["Lesson plan generator", "Worksheet creator", "Rubric builder", "Multiple subjects"],
    instructional_fit: "Reduces planning time with AI-generated materials.",
    implementation_notes: "Web-based. Individual accounts.",
    privacy_notes: "Teacher-facing tool.",
    accessibility_notes: "Web-accessible.",
    admin_integration_notes: "Individual tool.",
    editorial_verdict: "A straightforward lesson planning assistant in a growing category.",
    categories: ["Lesson Planning"], grade_bands: ["K-2", "3-5", "6-8", "9-12"], audiences: ["Teachers"],
    pricing_type: "Freemium", pricing_details: "Free tier. Premium available.",
    privacy_level: "Medium", accessibility_level: "Moderate",
    scores: { ease_of_use: 8, instructional_value: 7, data_privacy: 6, accessibility: 7 }, overall_score: 7.1,
    tags: ["lesson planning", "worksheets", "rubrics"],
    integrations: [],
    compliance_signals: [{ label: "FERPA Compliant", status: "unknown", url: null }],
    vpat_status: "not_available", vpat_url: null, vpat_notes: "No public VPAT found.",
    last_reviewed: "2026-02-25", reviewer_notes: "Basic but functional.",
    listing_tier: "basic", is_featured: false, featured_rank: null, is_sponsored: false, status: "published",
    similar_tools: ["magicschool-ai", "eduaide-ai"],
  },
  {
    slug: "flintk12", name: "Flint", vendor: "Flint K12",
    website: "https://flintk12.com", affiliate_url: "https://flintk12.com?ref=dai",
    logo_url: "/logos/flint.svg",
    description: "AI tutoring platform built for K–12 with teacher-controlled conversations, real-time monitoring, and curriculum alignment.",
    overview: "Flint allows teachers to create AI activities where students engage in guided conversations. Real-time monitoring, content controls, and curriculum alignment make it a strong choice for student-facing AI.",
    why_it_matters: "Purpose-built K–12 AI tutoring with best-in-class monitoring and safety.",
    best_for: ["Guided AI tutoring", "Socratic dialogue", "Curriculum-aligned activities", "Writing feedback"],
    not_ideal_for: ["Lesson planning", "Visual content", "Admin workflows"],
    key_features: ["Teacher-designed AI activities", "Real-time monitoring", "Curriculum alignment", "Writing feedback", "Rubric-based assessment"],
    instructional_fit: "Strong instructional design framework. Teachers control what the AI can discuss.",
    implementation_notes: "Web-based. Clever and Google SSO. Quick teacher onboarding.",
    privacy_notes: "FERPA, COPPA, and GDPR compliant. Student data never shared with third parties or used for AI training.",
    accessibility_notes: "Clean text-based interface. Keyboard navigable. Mobile responsive.",
    admin_integration_notes: "School and district plans. Admin dashboard with analytics.",
    editorial_verdict: "One of the best purpose-built K–12 AI tutoring platforms. Takes safety and instructional design seriously.",
    categories: ["Tutoring"], grade_bands: ["3-5", "6-8", "9-12"], audiences: ["Teachers", "Students"],
    pricing_type: "Freemium", pricing_details: "Free tier. Premium at $10/mo per teacher. District pricing available.",
    privacy_level: "High", accessibility_level: "Moderate",
    scores: { ease_of_use: 8, instructional_value: 9, data_privacy: 9, accessibility: 7 }, overall_score: 8.5,
    tags: ["AI tutoring", "K-12", "monitoring", "curriculum", "student-facing", "safe AI"],
    integrations: ["Google Classroom", "Clever", "Canvas"],
    compliance_signals: [
      { label: "FERPA Compliant", status: "available", url: "https://flintk12.com/security" },
      { label: "COPPA Compliant", status: "available", url: "https://flintk12.com/security" },
      { label: "GDPR Compliant", status: "available", url: "https://flintk12.com/dpia" },
      { label: "DPA Available", status: "available", url: "https://flintk12.com/privacy-policy" },
    ],
    vpat_status: "not_available", vpat_url: null, vpat_notes: "No public VPAT. Contact vendor.",
    last_reviewed: "2026-04-01", reviewer_notes: "Top-tier K–12 AI tutoring. Strong compliance posture.",
    listing_tier: "verified", is_featured: true, featured_rank: 9, is_sponsored: false, status: "published",
    similar_tools: ["schoolai", "khanmigo"],
  },
  {
    slug: "teachshare", name: "TeachShare", vendor: "TeachShare",
    website: "https://teachshare.com", affiliate_url: "https://teachshare.com?ref=dai",
    logo_url: "/logos/teachshare.svg",
    description: "AI-powered curriculum sharing and lesson design platform for collaborative teacher planning.",
    overview: "TeachShare helps teachers collaborate on curriculum design and share AI-generated lesson resources across departments and schools.",
    why_it_matters: "Collaborative curriculum planning with AI assistance.",
    best_for: ["Collaborative planning", "Curriculum sharing", "Department coordination"],
    not_ideal_for: ["Student-facing", "Assessment", "Individual lesson planning"],
    key_features: ["Collaborative planning", "AI lesson generation", "Resource sharing", "Curriculum mapping"],
    instructional_fit: "Good for PLC and department-level planning.",
    implementation_notes: "Web-based. School/district plans.",
    privacy_notes: "Teacher-facing. Minimal student data.",
    accessibility_notes: "Web-accessible.",
    admin_integration_notes: "School admin features.",
    editorial_verdict: "A collaborative planning tool with AI features for teams.",
    categories: ["Lesson Planning"], grade_bands: ["K-2", "3-5", "6-8", "9-12"], audiences: ["Teachers", "Curriculum Leaders"],
    pricing_type: "Freemium", pricing_details: "Free tier. School plans available.",
    privacy_level: "Medium", accessibility_level: "Moderate",
    scores: { ease_of_use: 7, instructional_value: 7, data_privacy: 7, accessibility: 7 }, overall_score: 7.0,
    tags: ["curriculum", "collaboration", "lesson planning", "PLC"],
    integrations: [],
    compliance_signals: [{ label: "FERPA Compliant", status: "partial", url: null }],
    vpat_status: "not_available", vpat_url: null, vpat_notes: "No public VPAT found.",
    last_reviewed: "2026-02-20", reviewer_notes: "Interesting collaborative approach.",
    listing_tier: "basic", is_featured: false, featured_rank: null, is_sponsored: false, status: "published",
    similar_tools: ["magicschool-ai", "groovelit"],
  },
  {
    slug: "education-copilot", name: "Education Copilot", vendor: "Education Copilot Inc.",
    website: "https://educationcopilot.com", affiliate_url: "https://educationcopilot.com?ref=dai",
    logo_url: "/logos/edcopilot.svg",
    description: "AI lesson planning platform that generates complete, print-ready lesson plans and handouts from simple prompts.",
    overview: "Education Copilot specializes in generating complete, print-ready educational materials including lesson plans, handouts, project outlines, and writing prompts.",
    why_it_matters: "Print-ready lesson plans and handouts from AI in minutes.",
    best_for: ["Lesson plan generation", "Handout creation", "Project-based learning design"],
    not_ideal_for: ["Student-facing AI", "Assessment grading", "Interactive activities"],
    key_features: ["Lesson plan templates", "Handout generator", "Project outlines", "Export to PDF/Word"],
    instructional_fit: "Strong for reducing planning time. Good for new teachers.",
    implementation_notes: "Web-based. Individual teacher setup in minutes.",
    privacy_notes: "FERPA compliant. Does not process student data.",
    accessibility_notes: "Web-accessible. Generated documents can be adapted.",
    admin_integration_notes: "No admin dashboard. Individual tool.",
    editorial_verdict: "A solid lesson planning tool with clean output. Best for individual teachers.",
    categories: ["Lesson Planning"], grade_bands: ["K-2", "3-5", "6-8", "9-12"], audiences: ["Teachers"],
    pricing_type: "Paid", pricing_details: "$9/mo per teacher. Annual plans available.",
    privacy_level: "Medium", accessibility_level: "Moderate",
    scores: { ease_of_use: 8, instructional_value: 8, data_privacy: 7, accessibility: 7 }, overall_score: 7.6,
    tags: ["lesson planning", "handouts", "templates", "print-ready"],
    integrations: ["Google Drive"],
    compliance_signals: [
      { label: "FERPA Compliant", status: "available", url: null },
      { label: "COPPA Compliant", status: "available", url: null },
    ],
    vpat_status: "not_available", vpat_url: null, vpat_notes: "No public VPAT found.",
    last_reviewed: "2026-02-10", reviewer_notes: "Solid individual teacher tool.",
    listing_tier: "basic", is_featured: false, featured_rank: null, is_sponsored: false, status: "published",
    similar_tools: ["magicschool-ai", "eduaide-ai"],
  },
  {
    slug: "curriculum-genie", name: "Curriculum Genie", vendor: "Curriculum Genie",
    website: "https://curriculumgenie.com", affiliate_url: "https://curriculumgenie.com?ref=dai",
    logo_url: "/logos/curriculumgenie.svg",
    description: "AI curriculum development tool that helps educators design standards-aligned scope and sequence plans.",
    overview: "Curriculum Genie uses AI to help build curriculum maps, scope and sequence documents, and unit plans aligned to standards.",
    why_it_matters: "AI-powered curriculum mapping and scope-and-sequence planning.",
    best_for: ["Curriculum mapping", "Scope and sequence", "Unit planning", "Standards alignment"],
    not_ideal_for: ["Daily lesson plans", "Student-facing", "Assessment"],
    key_features: ["Curriculum mapping", "Standards alignment", "Unit plan generator", "Scope and sequence"],
    instructional_fit: "Valuable for curriculum leaders doing big-picture planning.",
    implementation_notes: "Web-based. Check vendor for school plans.",
    privacy_notes: "Teacher/admin-facing tool.",
    accessibility_notes: "Web-accessible.",
    admin_integration_notes: "Designed for curriculum teams.",
    editorial_verdict: "A niche but valuable tool for curriculum directors and department heads.",
    categories: ["Lesson Planning"], grade_bands: ["K-2", "3-5", "6-8", "9-12"], audiences: ["Curriculum Leaders", "Teachers"],
    pricing_type: "Freemium", pricing_details: "Free tier. Premium plans available.",
    privacy_level: "Medium", accessibility_level: "Moderate",
    scores: { ease_of_use: 7, instructional_value: 8, data_privacy: 7, accessibility: 7 }, overall_score: 7.4,
    tags: ["curriculum", "mapping", "standards", "scope and sequence"],
    integrations: [],
    compliance_signals: [{ label: "FERPA Compliant", status: "unknown", url: null }],
    vpat_status: "not_available", vpat_url: null, vpat_notes: "No public VPAT found.",
    last_reviewed: "2026-02-15", reviewer_notes: "Good niche tool for curriculum teams.",
    listing_tier: "basic", is_featured: false, featured_rank: null, is_sponsored: false, status: "published",
    similar_tools: ["groovelit", "teachshare"],
  },
  {
    slug: "suno", name: "Suno", vendor: "Suno Inc.",
    website: "https://suno.com", affiliate_url: "https://suno.com?ref=dai",
    logo_url: "/logos/suno.svg",
    description: "AI music generation tool — create original songs and music from text prompts for creative classroom projects.",
    overview: "Suno generates original songs with vocals, instruments, and lyrics from text prompts. Teachers can create educational songs or use it for creative music projects.",
    why_it_matters: "Generate original songs from text — unique creative tool for classrooms.",
    best_for: ["Music creation", "Creative projects", "Mnemonics", "Arts integration"],
    not_ideal_for: ["Assessment", "Lesson planning", "Academic instruction"],
    key_features: ["Text-to-music", "Vocal generation", "Multiple genres", "Lyrics generation"],
    instructional_fit: "Creative arts integration. Educational mnemonics. Student creative expression.",
    implementation_notes: "Web-based. Individual accounts. Not education-specific.",
    privacy_notes: "General consumer platform. Not education-specific.",
    accessibility_notes: "Audio-based output. Lyrics provided as text.",
    admin_integration_notes: "No admin features.",
    editorial_verdict: "A unique creative tool that can add musical engagement to lessons, but not education-specific.",
    categories: ["Content Creation"], grade_bands: ["3-5", "6-8", "9-12"], audiences: ["Teachers", "Students"],
    pricing_type: "Freemium", pricing_details: "Free tier with limited generations. Pro at $10/mo.",
    privacy_level: "Medium", accessibility_level: "Moderate",
    scores: { ease_of_use: 8, instructional_value: 6, data_privacy: 5, accessibility: 6 }, overall_score: 6.3,
    tags: ["music", "creative", "audio", "songs", "arts"],
    integrations: [],
    compliance_signals: [{ label: "FERPA Compliant", status: "unknown", url: null }],
    vpat_status: "not_available", vpat_url: null, vpat_notes: "No VPAT. Not education-specific.",
    last_reviewed: "2026-03-05", reviewer_notes: "Fun creative tool. No compliance docs.",
    listing_tier: "basic", is_featured: false, featured_rank: null, is_sponsored: false, status: "published",
    similar_tools: [],
  },
  {
    slug: "google-notebooklm", name: "Google NotebookLM", vendor: "Google",
    website: "https://notebooklm.google.com", affiliate_url: "https://notebooklm.google.com?ref=dai",
    logo_url: "/logos/notebooklm.svg",
    description: "Google's AI research tool that generates insights, summaries, and study guides from uploaded documents — source-grounded to reduce hallucination.",
    overview: "NotebookLM lets users upload documents and get AI-generated summaries, Q&A, and study guides grounded exclusively in the uploaded sources, reducing AI hallucination.",
    why_it_matters: "Source-grounded AI research — reduces hallucination by only using uploaded documents.",
    best_for: ["Research synthesis", "Study guide creation", "Document analysis", "Source-grounded Q&A"],
    not_ideal_for: ["Live instruction", "Assessment", "Younger students"],
    key_features: ["Source-grounded AI", "Audio overview generation", "Study guide creation", "Citation tracking", "Multi-document analysis"],
    instructional_fit: "Excellent for research-based learning and higher-order thinking. Source-grounding teaches proper evidence use.",
    implementation_notes: "Free Google tool. Requires Google account.",
    privacy_notes: "Google account required. Data handling under Google's education terms for Workspace users.",
    accessibility_notes: "Google accessibility standards. Audio overviews add multimodal dimension.",
    admin_integration_notes: "No formal admin controls. Individual use.",
    editorial_verdict: "A powerful, source-grounded research tool from Google. Best for secondary and advanced learners.",
    categories: ["Student Support"], grade_bands: ["9-12"], audiences: ["Teachers", "Students"],
    pricing_type: "Free", pricing_details: "Free with Google account.",
    privacy_level: "High", accessibility_level: "Strong",
    scores: { ease_of_use: 8, instructional_value: 9, data_privacy: 8, accessibility: 8 }, overall_score: 8.4,
    tags: ["research", "study guides", "document analysis", "Google", "source-grounded"],
    integrations: ["Google Drive"],
    compliance_signals: [
      { label: "FERPA Compliant", status: "partial", url: "https://edu.google.com/intl/ALL_us/our-values/privacy-security/" },
      { label: "COPPA Compliant", status: "partial", url: "https://edu.google.com/intl/ALL_us/our-values/privacy-security/" },
    ],
    vpat_status: "on_request", vpat_url: "https://belonging.google/accessibility-conformance-reports/", vpat_notes: "Google product. Check ACR hub.",
    last_reviewed: "2026-03-28", reviewer_notes: "Innovative source-grounded approach. Strong for research.",
    listing_tier: "featured", is_featured: true, featured_rank: 10, is_sponsored: false, status: "published",
    similar_tools: ["perplexity"],
  },

  // ═══════════════════════════════════════════
  // TEACHING AIDES
  // ═══════════════════════════════════════════
  {
    slug: "padlet-ta", name: "Padlet TA", vendor: "Padlet",
    website: "https://padlet.com", affiliate_url: "https://padlet.com?ref=dai",
    logo_url: "/logos/padlet.svg",
    description: "AI teaching assistant integrated into Padlet's collaborative wall platform — generates discussion prompts and analyzes student contributions.",
    overview: "Padlet TA brings AI capabilities to Padlet's popular collaborative wall. Teachers can use AI for discussion prompts, content analysis, and activity design.",
    why_it_matters: "AI-enhanced collaborative walls — builds on a tool teachers already love.",
    best_for: ["Collaborative activities", "Discussion facilitation", "Visual organization", "Student collaboration"],
    not_ideal_for: ["Individual tutoring", "Assessment creation", "Detailed lesson planning"],
    key_features: ["AI-enhanced Padlet walls", "Discussion prompts", "Content analysis", "Multiple wall formats"],
    instructional_fit: "Builds on Padlet's strengths in collaborative learning with AI enhancement.",
    implementation_notes: "Available through Padlet platform. Familiar to many teachers.",
    privacy_notes: "FERPA and COPPA compliant for education accounts.",
    accessibility_notes: "Padlet's accessibility features apply. Visual nature may challenge some users.",
    admin_integration_notes: "School and district Padlet plans. Admin dashboard.",
    editorial_verdict: "A natural AI extension of an already-beloved tool. Best where Padlet is already adopted.",
    categories: ["Student Support"], grade_bands: ["3-5", "6-8", "9-12"], audiences: ["Teachers", "Students"],
    pricing_type: "Freemium", pricing_details: "Free tier with limited boards. School plans at $6/mo per teacher.",
    privacy_level: "Medium", accessibility_level: "Moderate",
    scores: { ease_of_use: 8, instructional_value: 7, data_privacy: 7, accessibility: 6 }, overall_score: 7.1,
    tags: ["collaboration", "discussion", "visual", "engagement"],
    integrations: ["Google Classroom", "Canvas", "Schoology", "Microsoft Teams"],
    compliance_signals: [
      { label: "FERPA Compliant", status: "available", url: null },
      { label: "COPPA Compliant", status: "available", url: null },
      { label: "DPA Available", status: "available", url: null },
    ],
    vpat_status: "not_available", vpat_url: null, vpat_notes: "No public VPAT found.",
    last_reviewed: "2026-02-28", reviewer_notes: "Familiar tool with thoughtful AI additions.",
    listing_tier: "basic", is_featured: false, featured_rank: null, is_sponsored: false, status: "published",
    similar_tools: ["curipod", "nearpod"],
  },
  {
    slug: "grouper", name: "Grouper", vendor: "Grouper",
    website: "https://grouper.app", affiliate_url: "https://grouper.app?ref=dai",
    logo_url: "/logos/grouper.svg",
    description: "AI-powered student grouping tool that creates balanced groups based on learning preferences, skill levels, and social dynamics.",
    overview: "Grouper uses AI to help teachers create optimized student groups for collaborative activities based on configurable criteria.",
    why_it_matters: "AI-optimized student grouping — saves time and creates better groups.",
    best_for: ["Student grouping", "Collaborative activities", "Differentiated groups"],
    not_ideal_for: ["Lesson planning", "Assessment", "Content creation"],
    key_features: ["AI group optimization", "Multiple criteria", "Quick regrouping", "History tracking"],
    instructional_fit: "Solves a common classroom pain point with smart automation.",
    implementation_notes: "Simple web tool. Quick setup.",
    privacy_notes: "Collects student names and grouping criteria. Check vendor for compliance.",
    accessibility_notes: "Simple web interface.",
    admin_integration_notes: "Individual teacher tool.",
    editorial_verdict: "A simple, focused tool that does one thing well — smart student grouping.",
    categories: ["Admin Tasks"], grade_bands: ["K-2", "3-5", "6-8", "9-12"], audiences: ["Teachers"],
    pricing_type: "Freemium", pricing_details: "Free basic. Premium available.",
    privacy_level: "Medium", accessibility_level: "Moderate",
    scores: { ease_of_use: 9, instructional_value: 6, data_privacy: 6, accessibility: 7 }, overall_score: 6.8,
    tags: ["grouping", "collaboration", "classroom management"],
    integrations: [],
    compliance_signals: [{ label: "FERPA Compliant", status: "unknown", url: null }],
    vpat_status: "not_available", vpat_url: null, vpat_notes: "No public VPAT found.",
    last_reviewed: "2026-02-20", reviewer_notes: "Simple and useful. Limited scope.",
    listing_tier: "basic", is_featured: false, featured_rank: null, is_sponsored: false, status: "published",
    similar_tools: [],
  },
  {
    slug: "goblin-tools", name: "Goblin Tools", vendor: "Arcology",
    website: "https://goblin.tools", affiliate_url: "https://goblin.tools?ref=dai",
    logo_url: "/logos/goblin.svg",
    description: "AI-powered task breakdown and executive function support tools designed for neurodivergent users and students with learning differences.",
    overview: "Goblin Tools is a collection of simple AI tools to help with executive function challenges. Magic To-Do breaks complex tasks into steps. Other tools help with tone, decisions, and time estimation.",
    why_it_matters: "Essential executive function support for neurodivergent learners — free and no account needed.",
    best_for: ["Executive function support", "Task breakdown", "Neurodivergent learners", "Special education"],
    not_ideal_for: ["Content creation", "Assessment", "Lesson planning"],
    key_features: ["Magic To-Do task breakdown", "Formalizer tone adjustment", "Judge decision support", "Estimator time estimation"],
    instructional_fit: "Uniquely valuable for supporting students with ADHD, autism, and executive function challenges.",
    implementation_notes: "Free web tool. No account required. Zero IT deployment.",
    privacy_notes: "Minimal data collection. No account needed. Data stored in browser only. No cookies.",
    accessibility_notes: "Simple, clean interface. Designed with neurodivergent users in mind.",
    admin_integration_notes: "No admin needed. Free individual tool.",
    editorial_verdict: "A gem for special education and inclusive classrooms. Simple, effective, privacy-friendly. Should be in every SpEd teacher's toolkit.",
    categories: ["Accessibility & Notes"], grade_bands: ["3-5", "6-8", "9-12"], audiences: ["Teachers", "Students"],
    pricing_type: "Free", pricing_details: "Free to use. Donation-supported.",
    privacy_level: "High", accessibility_level: "Strong",
    scores: { ease_of_use: 10, instructional_value: 7, data_privacy: 9, accessibility: 8 }, overall_score: 8.2,
    tags: ["executive function", "neurodivergent", "task management", "special education", "free"],
    integrations: [],
    compliance_signals: [
      { label: "FERPA Compliant", status: "available", url: "https://goblin.tools/Privacy" },
    ],
    vpat_status: "not_available", vpat_url: null, vpat_notes: "No formal VPAT. Privacy-by-design: no accounts, data stored locally only.",
    last_reviewed: "2026-03-18", reviewer_notes: "Outstanding accessibility tool. No compliance concerns — collects nothing.",
    listing_tier: "featured", is_featured: true, featured_rank: 11, is_sponsored: false, status: "published",
    similar_tools: ["diffit"],
  },

  // ═══════════════════════════════════════════
  // QUIZ / ASSESSMENT GENERATORS
  // ═══════════════════════════════════════════
  {
    slug: "questionwell", name: "QuestionWell", vendor: "QuestionWell",
    website: "https://questionwell.org", affiliate_url: "https://questionwell.org?ref=dai",
    logo_url: "/logos/questionwell.svg",
    description: "AI question generator that creates standards-aligned assessment items from any text, topic, or learning objective.",
    overview: "QuestionWell uses AI to generate high-quality assessment questions from any source material with standards alignment and Bloom's taxonomy levels.",
    why_it_matters: "Standards-aligned AI question generation — no student data collected at all.",
    best_for: ["Question generation", "Assessment creation", "Standards alignment", "Test prep"],
    not_ideal_for: ["Live classroom interaction", "Student-facing AI", "Visual content"],
    key_features: ["AI question generation", "Multiple question types", "Standards alignment", "Export to Google Forms", "Bloom's taxonomy"],
    instructional_fit: "Excellent for teachers who need rapid, quality assessment creation.",
    implementation_notes: "Simple web tool. Google SSO available.",
    privacy_notes: "FERPA and COPPA compliant. Does not collect ANY student data. Does not sell data.",
    accessibility_notes: "Clean web interface.",
    admin_integration_notes: "Individual and school licenses.",
    editorial_verdict: "A focused, effective assessment tool. Does one thing exceptionally well. Zero student data collection.",
    categories: ["Assessment"], grade_bands: ["3-5", "6-8", "9-12"], audiences: ["Teachers", "Curriculum Leaders"],
    pricing_type: "Freemium", pricing_details: "Free tier with limited questions. Premium at $5/mo.",
    privacy_level: "High", accessibility_level: "Moderate",
    scores: { ease_of_use: 9, instructional_value: 8, data_privacy: 9, accessibility: 7 }, overall_score: 8.3,
    tags: ["assessment", "question generation", "standards", "quiz", "FERPA"],
    integrations: ["Google Forms", "Google Classroom"],
    compliance_signals: [
      { label: "FERPA Compliant", status: "available", url: "https://questionwell.org/our-pledge" },
      { label: "COPPA Compliant", status: "available", url: "https://questionwell.org/our-pledge" },
    ],
    vpat_status: "not_available", vpat_url: null, vpat_notes: "No public VPAT found.",
    last_reviewed: "2026-03-15", reviewer_notes: "Excellent privacy posture. Zero student data.",
    listing_tier: "featured", is_featured: false, featured_rank: null, is_sponsored: false, status: "published",
    similar_tools: ["conker", "quizizz-ai"],
  },
  {
    slug: "wayground", name: "Wayground", vendor: "Wayground",
    website: "https://wayground.com", affiliate_url: "https://wayground.com?ref=dai",
    logo_url: "/logos/wayground.svg",
    description: "AI-powered district policy and AI governance platform that helps evaluate AI tools and manage adoption frameworks.",
    overview: "Wayground helps districts create, manage, and enforce AI usage policies. Provides evaluation rubrics and compliance tracking for AI tool adoption.",
    why_it_matters: "The governance layer districts need to manage AI tool adoption safely.",
    best_for: ["District AI governance", "Tool evaluation frameworks", "Policy management", "Compliance tracking"],
    not_ideal_for: ["Classroom instruction", "Student-facing", "Content creation"],
    key_features: ["Policy builder", "AI tool evaluation rubrics", "Compliance tracking", "Board reporting"],
    instructional_fit: "Not instructional — infrastructure for safe AI adoption decisions.",
    implementation_notes: "Requires district administrator engagement.",
    privacy_notes: "Handles policy documents, not student data. SOC 2 compliant.",
    accessibility_notes: "Admin interface meets WCAG standards.",
    admin_integration_notes: "Built for administrators. Multi-district support.",
    editorial_verdict: "Essential for districts serious about AI governance. Fills a critical infrastructure gap.",
    categories: ["Admin Tasks"], grade_bands: ["K-2", "3-5", "6-8", "9-12"], audiences: ["Administrators", "Curriculum Leaders"],
    pricing_type: "Paid", pricing_details: "Custom pricing based on district size.",
    privacy_level: "High", accessibility_level: "Moderate",
    scores: { ease_of_use: 7, instructional_value: 6, data_privacy: 9, accessibility: 7 }, overall_score: 7.1,
    tags: ["governance", "policy", "admin", "compliance", "evaluation"],
    integrations: [],
    compliance_signals: [
      { label: "SOC 2 Type II", status: "available", url: null },
      { label: "DPA Available", status: "available", url: null },
    ],
    vpat_status: "not_available", vpat_url: null, vpat_notes: "Contact vendor for accessibility documentation.",
    last_reviewed: "2026-03-25", reviewer_notes: "Unique in the market. Addresses critical governance gap.",
    listing_tier: "featured", is_featured: false, featured_rank: null, is_sponsored: false, status: "published",
    similar_tools: [],
  },
  {
    slug: "gibbly", name: "Gibbly", vendor: "Gibbly",
    website: "https://gibbly.co", affiliate_url: "https://gibbly.co?ref=dai",
    logo_url: "/logos/gibbly.svg",
    description: "AI quiz and assessment generator that creates interactive quizzes from any topic in seconds.",
    overview: "Gibbly uses AI to generate quizzes, flashcards, and assessment activities from text prompts or uploaded content.",
    why_it_matters: "Instant AI quiz generation from any topic or uploaded text.",
    best_for: ["Quiz generation", "Formative assessment", "Review activities"],
    not_ideal_for: ["Lesson planning", "Deep differentiation", "Admin tasks"],
    key_features: ["AI quiz generation", "Multiple question types", "Student engagement", "Quick creation"],
    instructional_fit: "Good for quick formative checks and review.",
    implementation_notes: "Web-based. Easy setup.",
    privacy_notes: "Check vendor for current compliance status.",
    accessibility_notes: "Web-accessible.",
    admin_integration_notes: "Basic school features.",
    editorial_verdict: "A quick quiz generator in a competitive category.",
    categories: ["Assessment"], grade_bands: ["K-2", "3-5", "6-8", "9-12"], audiences: ["Teachers", "Students"],
    pricing_type: "Freemium", pricing_details: "Free tier. Premium available.",
    privacy_level: "Medium", accessibility_level: "Moderate",
    scores: { ease_of_use: 8, instructional_value: 7, data_privacy: 6, accessibility: 7 }, overall_score: 7.1,
    tags: ["quiz", "assessment", "formative", "AI generation"],
    integrations: [],
    compliance_signals: [{ label: "FERPA Compliant", status: "partial", url: null }],
    vpat_status: "not_available", vpat_url: null, vpat_notes: "No public VPAT found.",
    last_reviewed: "2026-02-28", reviewer_notes: "Solid quiz tool in a crowded field.",
    listing_tier: "basic", is_featured: false, featured_rank: null, is_sponsored: false, status: "published",
    similar_tools: ["conker", "quizizz-ai", "questionwell"],
  },
  {
    slug: "conker", name: "Conker", vendor: "Conker",
    website: "https://conker.ai", affiliate_url: "https://conker.ai?ref=dai",
    logo_url: "/logos/conker.svg",
    description: "AI quiz builder with FERPA/COPPA compliance that creates personalized, standards-aligned assessments for K–12 classrooms.",
    overview: "Conker generates engaging, personalized assessments aligned to standards. Compliant with FERPA, COPPA, and GDPR. Does not sell student data or target ads to minors.",
    why_it_matters: "Compliant AI quiz builder — FERPA, COPPA, GDPR certified.",
    best_for: ["Standards-aligned quizzes", "Formative assessment", "Differentiated assessment"],
    not_ideal_for: ["Lesson planning", "Content creation", "Admin tasks"],
    key_features: ["AI quiz generation", "Standards alignment", "Multiple formats", "Differentiation", "Student analytics"],
    instructional_fit: "Strong standards alignment with differentiation capabilities.",
    implementation_notes: "Web-based. Google Classroom integration.",
    privacy_notes: "FERPA, COPPA, and GDPR compliant. Does not sell personal information. No targeted ads to minors.",
    accessibility_notes: "Web-accessible. Check for current WCAG status.",
    admin_integration_notes: "School plans available.",
    editorial_verdict: "A well-designed, compliant quiz platform with genuine differentiation features.",
    categories: ["Assessment"], grade_bands: ["K-2", "3-5", "6-8", "9-12"], audiences: ["Teachers", "Students"],
    pricing_type: "Freemium", pricing_details: "Free tier. Pro plans available.",
    privacy_level: "High", accessibility_level: "Moderate",
    scores: { ease_of_use: 8, instructional_value: 8, data_privacy: 9, accessibility: 7 }, overall_score: 8.1,
    tags: ["quiz", "assessment", "standards", "differentiation", "FERPA", "COPPA"],
    integrations: ["Google Classroom"],
    compliance_signals: [
      { label: "FERPA Compliant", status: "available", url: "https://www.conker.ai/legal/privacy" },
      { label: "COPPA Compliant", status: "available", url: "https://www.conker.ai/legal/privacy" },
      { label: "GDPR Compliant", status: "available", url: "https://www.conker.ai/legal/privacy" },
    ],
    vpat_status: "not_available", vpat_url: null, vpat_notes: "No public VPAT found.",
    last_reviewed: "2026-03-22", reviewer_notes: "Strong compliance and differentiation. Recommended.",
    listing_tier: "featured", is_featured: false, featured_rank: null, is_sponsored: false, status: "published",
    similar_tools: ["questionwell", "quizizz-ai", "gibbly"],
  },

  // ═══════════════════════════════════════════
  // REFLECTION, FEEDBACK & COLLABORATION
  // ═══════════════════════════════════════════
  {
    slug: "mirrortalk", name: "MirrorTalk", vendor: "MirrorTalk",
    website: "https://mirrortalk.ai", affiliate_url: "https://mirrortalk.ai?ref=dai",
    logo_url: "/logos/mirrortalk.svg",
    description: "AI-powered speaking and presentation practice tool — students rehearse and get AI feedback on communication skills.",
    overview: "MirrorTalk helps students practice speaking, presentations, and interview skills with AI-powered feedback on delivery, content, and communication.",
    why_it_matters: "AI speaking coach — students practice and get feedback without judgment.",
    best_for: ["Presentation practice", "Speaking skills", "Interview prep", "Communication development"],
    not_ideal_for: ["Written assessment", "Lesson planning", "Content creation"],
    key_features: ["AI speaking analysis", "Presentation practice", "Feedback on delivery", "Progress tracking"],
    instructional_fit: "Fills a gap in communication skills development.",
    implementation_notes: "Web-based. Requires microphone access.",
    privacy_notes: "Processes voice recordings. Check vendor for data handling details.",
    accessibility_notes: "Voice-based. May not suit all learners.",
    admin_integration_notes: "School features available.",
    editorial_verdict: "An innovative tool for communication skills development.",
    categories: ["Student Support"], grade_bands: ["6-8", "9-12"], audiences: ["Teachers", "Students"],
    pricing_type: "Freemium", pricing_details: "Free tier. School plans available.",
    privacy_level: "Medium", accessibility_level: "Moderate",
    scores: { ease_of_use: 7, instructional_value: 8, data_privacy: 6, accessibility: 5 }, overall_score: 6.9,
    tags: ["speaking", "presentation", "communication", "feedback"],
    integrations: [],
    compliance_signals: [{ label: "FERPA Compliant", status: "partial", url: null }],
    vpat_status: "not_available", vpat_url: null, vpat_notes: "No public VPAT found.",
    last_reviewed: "2026-03-01", reviewer_notes: "Innovative. Voice data handling needs verification.",
    listing_tier: "basic", is_featured: false, featured_rank: null, is_sponsored: false, status: "published",
    similar_tools: ["snorkl"],
  },
  {
    slug: "gotfeedback", name: "gotFeedback", vendor: "gotLearning",
    website: "https://gotlearning.com", affiliate_url: "https://gotlearning.com?ref=dai",
    logo_url: "/logos/gotfeedback.svg",
    description: "AI-powered feedback tool that helps teachers provide personalized, constructive feedback on student work faster.",
    overview: "gotFeedback by gotLearning uses AI to help teachers generate personalized feedback on student assignments, reducing grading time while maintaining quality.",
    why_it_matters: "AI-accelerated teacher feedback — personalized, not generic.",
    best_for: ["Student feedback", "Grading acceleration", "Personalized comments"],
    not_ideal_for: ["Lesson planning", "Interactive activities", "Student-facing AI"],
    key_features: ["AI feedback generation", "Personalization", "Multiple assignment types", "Teacher customization"],
    instructional_fit: "Reduces feedback burden while maintaining personalization.",
    implementation_notes: "Web-based. Check for LMS integrations.",
    privacy_notes: "Processes student work. Check vendor for current compliance.",
    accessibility_notes: "Web-accessible.",
    admin_integration_notes: "School features may be available.",
    editorial_verdict: "Addresses a real pain point — teacher feedback at scale.",
    categories: ["Feedback & Grading"], grade_bands: ["3-5", "6-8", "9-12"], audiences: ["Teachers"],
    pricing_type: "Freemium", pricing_details: "Free tier. Premium available.",
    privacy_level: "Medium", accessibility_level: "Moderate",
    scores: { ease_of_use: 8, instructional_value: 8, data_privacy: 6, accessibility: 7 }, overall_score: 7.4,
    tags: ["feedback", "grading", "personalized", "assessment"],
    integrations: [],
    compliance_signals: [{ label: "FERPA Compliant", status: "partial", url: null }],
    vpat_status: "not_available", vpat_url: null, vpat_notes: "No public VPAT found.",
    last_reviewed: "2026-03-08", reviewer_notes: "Useful feedback tool. Compliance needs verification.",
    listing_tier: "basic", is_featured: false, featured_rank: null, is_sponsored: false, status: "published",
    similar_tools: ["brisk-teaching"],
  },
  {
    slug: "enlightai", name: "EnlightAI", vendor: "EnlightAI",
    website: "https://enlightai.com", affiliate_url: "https://enlightai.com?ref=dai",
    logo_url: "/logos/enlightai.svg",
    description: "AI-powered reflection and metacognition tool that helps students develop self-awareness about their learning process.",
    overview: "EnlightAI uses AI to guide students through structured reflection on their learning, helping develop metacognitive skills.",
    why_it_matters: "AI-guided metacognition — helps students think about their thinking.",
    best_for: ["Student reflection", "Metacognition", "Learning journals", "Self-assessment"],
    not_ideal_for: ["Lesson planning", "Quiz generation", "Admin tasks"],
    key_features: ["Guided reflection prompts", "AI feedback on reflections", "Progress tracking", "Learning journals"],
    instructional_fit: "Supports SEL and metacognitive skill development.",
    implementation_notes: "Web-based.",
    privacy_notes: "Check vendor for current compliance documentation.",
    accessibility_notes: "Web-accessible.",
    admin_integration_notes: "Teacher dashboard for student reflections.",
    editorial_verdict: "An interesting metacognition tool worth watching as it develops.",
    categories: ["Student Support"], grade_bands: ["6-8", "9-12"], audiences: ["Teachers", "Students"],
    pricing_type: "Freemium", pricing_details: "Free tier available.",
    privacy_level: "Medium", accessibility_level: "Moderate",
    scores: { ease_of_use: 7, instructional_value: 8, data_privacy: 6, accessibility: 7 }, overall_score: 7.2,
    tags: ["metacognition", "reflection", "SEL", "self-assessment"],
    integrations: [],
    compliance_signals: [{ label: "FERPA Compliant", status: "unknown", url: null }],
    vpat_status: "not_available", vpat_url: null, vpat_notes: "No public VPAT found.",
    last_reviewed: "2026-02-25", reviewer_notes: "Interesting niche. Early stage.",
    listing_tier: "basic", is_featured: false, featured_rank: null, is_sponsored: false, status: "published",
    similar_tools: ["snorkl"],
  },
  {
    slug: "figjam-ai", name: "FigJam AI", vendor: "Figma",
    website: "https://figma.com/figjam", affiliate_url: "https://figma.com/figjam?ref=dai",
    logo_url: "/logos/figjam.svg",
    description: "Figma's AI-powered collaborative whiteboard with Jambot AI assistant for brainstorming, planning, and visual thinking.",
    overview: "FigJam combines a collaborative whiteboard with AI features. Jambot generates ideas, summarizes content, and helps organize visual thinking.",
    why_it_matters: "AI-powered collaborative whiteboard for visual brainstorming and planning.",
    best_for: ["Brainstorming", "Visual thinking", "Collaborative planning", "Design thinking"],
    not_ideal_for: ["Assessment", "Grading", "Direct instruction"],
    key_features: ["AI Jambot assistant", "Collaborative whiteboard", "Templates", "Sticky notes", "Diagramming"],
    instructional_fit: "Excellent for design thinking, brainstorming, and collaborative visual activities.",
    implementation_notes: "Free for education. Web-based.",
    privacy_notes: "Figma's enterprise privacy framework. Education plans available.",
    accessibility_notes: "Web-accessible. Keyboard shortcuts available.",
    admin_integration_notes: "Education team management.",
    editorial_verdict: "A powerful collaborative whiteboard with useful AI features. Free for education.",
    categories: ["Content Creation"], grade_bands: ["6-8", "9-12"], audiences: ["Teachers", "Students"],
    pricing_type: "Free", pricing_details: "Free for education use.",
    privacy_level: "Medium", accessibility_level: "Moderate",
    scores: { ease_of_use: 8, instructional_value: 7, data_privacy: 7, accessibility: 7 }, overall_score: 7.3,
    tags: ["whiteboard", "collaboration", "brainstorming", "design thinking", "visual"],
    integrations: [],
    compliance_signals: [{ label: "FERPA Compliant", status: "partial", url: null }],
    vpat_status: "not_available", vpat_url: null, vpat_notes: "No VPAT for FigJam specifically.",
    last_reviewed: "2026-03-10", reviewer_notes: "Great for collaborative visual work. Free for education.",
    listing_tier: "basic", is_featured: false, featured_rank: null, is_sponsored: false, status: "published",
    similar_tools: ["padlet-ta", "canva"],
  },
  {
    slug: "snorkl", name: "Snorkl", vendor: "Snorkl",
    website: "https://snorkl.app", affiliate_url: "https://snorkl.app?ref=dai",
    logo_url: "/logos/snorkl.svg",
    description: "AI assessment tool where students explain their thinking through voice and whiteboard recordings, receiving instant AI feedback.",
    overview: "Snorkl lets students record verbal explanations with a digital whiteboard. AI provides instant feedback on reasoning, not just answers. iKeepSafe FERPA/COPPA certified.",
    why_it_matters: "Students explain thinking verbally + AI gives feedback on reasoning — not just answers.",
    best_for: ["Student thinking assessment", "Verbal explanations", "Metacognition", "Formative assessment"],
    not_ideal_for: ["Written assessment", "Lesson planning", "Admin tasks"],
    key_features: ["Voice + whiteboard recording", "AI feedback on reasoning", "Teacher review dashboard", "FERPA/COPPA certified"],
    instructional_fit: "Uniquely assesses student thinking processes, not just final answers.",
    implementation_notes: "Web-based. Requires microphone. Quick teacher setup.",
    privacy_notes: "iKeepSafe FERPA, COPPA, and CSPC certified. Proactively removes PII before sending to OpenAI.",
    accessibility_notes: "Voice-based input. Digital whiteboard for visual explanations.",
    admin_integration_notes: "Teacher dashboard for reviewing student recordings.",
    editorial_verdict: "A uniquely valuable assessment tool that captures student thinking. Strong compliance posture.",
    categories: ["Assessment"], grade_bands: ["3-5", "6-8", "9-12"], audiences: ["Teachers", "Students"],
    pricing_type: "Freemium", pricing_details: "Free tier. School plans available.",
    privacy_level: "High", accessibility_level: "Moderate",
    scores: { ease_of_use: 8, instructional_value: 9, data_privacy: 9, accessibility: 6 }, overall_score: 8.2,
    tags: ["assessment", "student thinking", "voice", "feedback", "metacognition", "FERPA"],
    integrations: ["Google Classroom"],
    compliance_signals: [
      { label: "FERPA Compliant", status: "available", url: "https://snorkl.app/safety" },
      { label: "COPPA Compliant", status: "available", url: "https://snorkl.app/safety" },
    ],
    vpat_status: "not_available", vpat_url: null, vpat_notes: "No public VPAT. iKeepSafe certified for FERPA/COPPA.",
    last_reviewed: "2026-03-20", reviewer_notes: "Innovative assessment approach. Strong compliance via iKeepSafe.",
    listing_tier: "featured", is_featured: false, featured_rank: null, is_sponsored: false, status: "published",
    similar_tools: ["formative", "mirrortalk"],
  },
  {
    slug: "class-companion", name: "Class Companion", vendor: "Class Companion",
    website: "https://classcompanion.com", affiliate_url: "https://classcompanion.com?ref=dai",
    logo_url: "/logos/classcompanion.svg",
    description: "AI-powered writing and discussion feedback tool that gives students detailed, rubric-based feedback on open-ended responses.",
    overview: "Class Companion uses AI to provide detailed, rubric-aligned feedback on student writing and discussion responses, helping teachers scale personalized feedback.",
    why_it_matters: "Rubric-based AI feedback on student writing — scales what good teachers do.",
    best_for: ["Writing feedback", "Discussion responses", "Rubric-based assessment", "ELA instruction"],
    not_ideal_for: ["Math", "Visual content", "Admin tasks"],
    key_features: ["AI rubric-based feedback", "Writing analysis", "Discussion scoring", "Teacher customization"],
    instructional_fit: "Extends teacher feedback capacity without sacrificing quality.",
    implementation_notes: "Web-based. LMS integrations available.",
    privacy_notes: "Education-focused. Check vendor for current compliance.",
    accessibility_notes: "Web-accessible.",
    admin_integration_notes: "School plans with teacher management.",
    editorial_verdict: "A promising feedback tool that aligns AI output to teacher rubrics.",
    categories: ["Feedback & Grading"], grade_bands: ["6-8", "9-12"], audiences: ["Teachers", "Students"],
    pricing_type: "Freemium", pricing_details: "Free tier. School plans available.",
    privacy_level: "Medium", accessibility_level: "Moderate",
    scores: { ease_of_use: 7, instructional_value: 8, data_privacy: 6, accessibility: 7 }, overall_score: 7.2,
    tags: ["feedback", "writing", "rubric", "discussion", "ELA"],
    integrations: ["Google Classroom", "Canvas"],
    compliance_signals: [{ label: "FERPA Compliant", status: "partial", url: null }],
    vpat_status: "not_available", vpat_url: null, vpat_notes: "No public VPAT found.",
    last_reviewed: "2026-03-05", reviewer_notes: "Rubric alignment is a differentiator.",
    listing_tier: "basic", is_featured: false, featured_rank: null, is_sponsored: false, status: "published",
    similar_tools: ["gotfeedback", "brisk-teaching"],
  },
  {
    slug: "parlay-genie", name: "Parlay Genie", vendor: "Parlay",
    website: "https://parlayideas.com", affiliate_url: "https://parlayideas.com?ref=dai",
    logo_url: "/logos/parlay.svg",
    description: "AI-powered discussion facilitation tool that generates discussion prompts, tracks participation, and develops student dialogue skills.",
    overview: "Parlay uses AI to facilitate classroom discussions with smart prompts, participation tracking, and peer feedback. Recognized by Harvard GSE for pedagogically sound AI use in discussions.",
    why_it_matters: "AI-facilitated discussions — Harvard GSE recognized for pedagogical soundness.",
    best_for: ["Discussion facilitation", "Socratic seminars", "Participation tracking", "Critical thinking"],
    not_ideal_for: ["Assessment generation", "Lesson planning", "Admin tasks"],
    key_features: ["AI discussion prompts", "Participation tracking", "Peer feedback", "Discussion analytics"],
    instructional_fit: "Supports student discourse and higher-order thinking through structured discussion.",
    implementation_notes: "Web-based. Google Classroom integration.",
    privacy_notes: "Education-focused. Check vendor for current compliance documentation.",
    accessibility_notes: "Web-accessible. Text-based discussion.",
    admin_integration_notes: "School plans with teacher management.",
    editorial_verdict: "A well-designed discussion tool with genuine pedagogical foundations.",
    categories: ["Student Support"], grade_bands: ["6-8", "9-12"], audiences: ["Teachers", "Students"],
    pricing_type: "Freemium", pricing_details: "Free tier. School plans available.",
    privacy_level: "Medium", accessibility_level: "Moderate",
    scores: { ease_of_use: 8, instructional_value: 9, data_privacy: 6, accessibility: 7 }, overall_score: 7.8,
    tags: ["discussion", "Socratic", "participation", "critical thinking", "dialogue"],
    integrations: ["Google Classroom"],
    compliance_signals: [{ label: "FERPA Compliant", status: "partial", url: null }],
    vpat_status: "not_available", vpat_url: null, vpat_notes: "No public VPAT found.",
    last_reviewed: "2026-03-15", reviewer_notes: "Strong pedagogy. Harvard GSE recognition is notable.",
    listing_tier: "featured", is_featured: false, featured_rank: null, is_sponsored: false, status: "published",
    similar_tools: ["padlet-ta", "curipod"],
  },
  {
    slug: "quillbot", name: "QuillBot", vendor: "QuillBot (Course Hero)",
    website: "https://quillbot.com", affiliate_url: "https://quillbot.com?ref=dai",
    logo_url: "/logos/quillbot.svg",
    description: "AI paraphrasing and writing tool that helps students improve writing clarity, rephrase text, and develop vocabulary.",
    overview: "QuillBot uses AI to paraphrase, summarize, and improve writing. Students can rephrase text to improve clarity while learning vocabulary and sentence structure.",
    why_it_matters: "AI paraphrasing that helps students learn to rephrase — not just copy.",
    best_for: ["Paraphrasing practice", "Writing improvement", "Vocabulary development", "Summarization"],
    not_ideal_for: ["Original writing assessment", "Math", "Interactive activities"],
    key_features: ["AI paraphrasing", "Summarizer", "Grammar checker", "Citation generator", "Multiple writing modes"],
    instructional_fit: "Useful for developing paraphrasing skills. Teachers should set clear expectations about appropriate use.",
    implementation_notes: "Web-based. Browser extension. Individual accounts.",
    privacy_notes: "General consumer platform. Education-specific plans under development.",
    accessibility_notes: "Web and browser extension accessible.",
    admin_integration_notes: "Limited school admin features.",
    editorial_verdict: "A useful writing tool when used with clear classroom expectations about paraphrasing vs. original work.",
    categories: ["Writing Support"], grade_bands: ["6-8", "9-12"], audiences: ["Teachers", "Students"],
    pricing_type: "Freemium", pricing_details: "Free basic features. Premium at $10/mo.",
    privacy_level: "Medium", accessibility_level: "Moderate",
    scores: { ease_of_use: 9, instructional_value: 7, data_privacy: 5, accessibility: 7 }, overall_score: 7.1,
    tags: ["paraphrasing", "writing", "vocabulary", "summarization"],
    integrations: ["Google Docs", "Microsoft Word"],
    compliance_signals: [{ label: "FERPA Compliant", status: "unknown", url: null }],
    vpat_status: "not_available", vpat_url: null, vpat_notes: "No public VPAT found.",
    last_reviewed: "2026-02-18", reviewer_notes: "Useful with guardrails. Academic integrity concerns if misused.",
    listing_tier: "basic", is_featured: false, featured_rank: null, is_sponsored: false, status: "published",
    similar_tools: ["grammarly", "wewillwrite"],
  },
  {
    slug: "chat-pdf", name: "Chat PDF", vendor: "Chat PDF",
    website: "https://chatpdf.com", affiliate_url: "https://chatpdf.com?ref=dai",
    logo_url: "/logos/chatpdf.svg",
    description: "AI tool that lets you chat with any PDF document — upload a textbook, article, or handout and ask questions about its content.",
    overview: "Chat PDF allows users to upload any PDF and have an AI conversation about its contents. Useful for teachers and students working with long documents.",
    why_it_matters: "Turn any PDF into an interactive Q&A — great for textbook analysis.",
    best_for: ["Document analysis", "Textbook Q&A", "Research reading", "Study aid"],
    not_ideal_for: ["Content creation", "Live instruction", "Assessment"],
    key_features: ["PDF upload and analysis", "Q&A about content", "Citation to specific pages", "Multiple document support"],
    instructional_fit: "Useful for helping students engage with complex texts and documents.",
    implementation_notes: "Web-based. Free tier available.",
    privacy_notes: "General consumer platform. Documents uploaded to servers for processing.",
    accessibility_notes: "Web-accessible. Text-based interaction.",
    admin_integration_notes: "No admin features.",
    editorial_verdict: "A useful document analysis tool. Be cautious about uploading sensitive materials.",
    categories: ["Student Support"], grade_bands: ["9-12"], audiences: ["Teachers", "Students"],
    pricing_type: "Freemium", pricing_details: "Free tier with limits. Pro plans available.",
    privacy_level: "Medium", accessibility_level: "Moderate",
    scores: { ease_of_use: 8, instructional_value: 7, data_privacy: 5, accessibility: 7 }, overall_score: 6.9,
    tags: ["PDF", "document analysis", "Q&A", "research", "study"],
    integrations: [],
    compliance_signals: [{ label: "FERPA Compliant", status: "unknown", url: null }],
    vpat_status: "not_available", vpat_url: null, vpat_notes: "No public VPAT found.",
    last_reviewed: "2026-02-10", reviewer_notes: "Useful but be cautious with sensitive documents.",
    listing_tier: "basic", is_featured: false, featured_rank: null, is_sponsored: false, status: "published",
    similar_tools: ["google-notebooklm", "perplexity"],
  },
];
