import type { Tool, PrivacyFlag, SavedView } from "./types";
import { newTools } from "./new-tools";

function derivePrivacyFlag(privacyLevel: Tool["privacy_level"]): PrivacyFlag {
  if (privacyLevel === "High") return "District Ready";
  if (privacyLevel === "Medium") return "Teacher Use Only";
  return "Use Caution";
}

type RawTool = Omit<Tool, "privacy_flag">;

const rawTools: RawTool[] = [
  {
    id: "1", slug: "magicschool-ai", name: "MagicSchool AI", vendor: "MagicSchool",
    website: "https://magicschool.ai", affiliate_url: "https://magicschool.ai?ref=dai",
    logo_url: "/logos/magicschool.svg",
    description: "AI-powered lesson planning and administrative task automation built specifically for K–12 educators.",
    overview: "MagicSchool AI provides over 60 AI tools designed specifically for teachers, covering lesson planning, differentiation, assessment creation, IEP drafting, and communication. It is one of the most comprehensive AI platforms built for K–12 education with a strong focus on reducing teacher workload.",
    why_it_matters: "Built specifically for teachers; reduces planning time significantly.",
    best_for: ["Lesson planning", "Differentiation", "IEP drafting", "Assessment creation", "Parent communication"],
    not_ideal_for: ["Student-facing AI interactions", "Real-time classroom polling", "Video content creation"],
    key_features: ["60+ AI tools for educators", "Lesson plan generator", "Rubric builder", "IEP assistant", "Text rewriter by grade level", "Quiz generator"],
    instructional_fit: "Excellent for reducing teacher planning time. Supports UDL-aligned differentiation and can generate materials across Bloom's taxonomy levels.",
    implementation_notes: "No LMS integration required for basic use. Supports Google and Clever SSO. Can be deployed in under a week with minimal IT support.",
    privacy_notes: "Education-focused but still AI-based. SOC 2 Type II compliant. Student data is never used for model training. Signed DPAs available for districts. COPPA and FERPA compliant.",
    accessibility_notes: "WCAG 2.1 AA compliant interface. Generated content can be adapted for reading level and language. Moderate overall accessibility posture.",
    admin_integration_notes: "Admin dashboard for usage monitoring. Supports district-wide deployment with role-based access. API available for enterprise customers.",
    editorial_verdict: "One of the most mature and teacher-specific AI platforms available. Excellent breadth of tools makes it a top recommendation for districts beginning their AI journey.",
    categories: ["Lesson Planning", "Admin Tasks"],
    grade_bands: ["K-2", "3-5", "6-8", "9-12"],
    audiences: ["Teachers", "Instructional Coaches", "Curriculum Leaders"],
    pricing_type: "Freemium",
    pricing_details: "Free tier with limited uses. Premium at $9.99/mo per teacher. District pricing available.",
    privacy_level: "Medium",
    accessibility_level: "Moderate",
    scores: { ease_of_use: 9, instructional_value: 9, data_privacy: 7, accessibility: 7 },
    overall_score: 8.4,
    tags: ["lesson planning", "differentiation", "AI writing", "assessment", "IEP", "admin"],
    integrations: ["Google Classroom", "Clever", "Canvas"],
    compliance_signals: [
      { label: "FERPA Compliant", status: "available", url: "https://www.magicschool.ai/privacy" },
      { label: "COPPA Compliant", status: "available", url: "https://www.magicschool.ai/privacy" },
      { label: "SOC 2 Type II", status: "available", url: "https://www.magicschool.ai/privacy" },
      { label: "DPA Available", status: "available", url: "https://www.magicschool.ai/privacy" },
    ],
    last_reviewed: "2026-03-15",
    reviewer_notes: "Reviewed by the District AI Index editorial team. Verified privacy documentation and conducted usability testing.",
        vpat_status: "available" as const, vpat_url: "https://www.magicschool.ai/accessibility", vpat_notes: "VPAT 2.5 published. WCAG AA 2.2 conformance. Available on accessibility page.",
listing_tier: "featured", is_featured: true, featured_rank: 1, is_sponsored: false, status: "published",
    similar_tools: ["eduaide-ai", "diffit", "brisk-teaching"],
  },
  {
    id: "2", slug: "khanmigo", name: "Khanmigo", vendor: "Khan Academy",
    website: "https://khanacademy.org/khan-labs", affiliate_url: "https://khanacademy.org/khan-labs?ref=dai",
    logo_url: "/logos/khanmigo.svg",
    description: "AI tutor powered by GPT-4 that guides students through learning with Socratic questioning, backed by Khan Academy's trusted education platform.",
    overview: "Khanmigo is Khan Academy's AI-powered tutor that uses Socratic questioning to help students learn without giving away answers. It serves as both a student tutor and teacher assistant, integrated deeply into the Khan Academy learning ecosystem.",
    why_it_matters: "One of the most structured, safe AI tutoring environments.",
    best_for: ["Math tutoring", "Socratic learning", "Student practice", "SAT prep", "Writing coaching"],
    not_ideal_for: ["Content creation for teachers", "Districts not using Khan Academy", "Visual content"],
    key_features: ["Socratic tutoring", "Math step-by-step help", "Writing coach", "Debate practice", "Teacher activity summaries"],
    instructional_fit: "Deeply aligned with learning science principles. The Socratic approach ensures students build understanding rather than receiving answers.",
    implementation_notes: "Requires Khan Academy district integration. Available through Khan Academy's district program.",
    privacy_notes: "High privacy — backed by Khan Academy's established nonprofit privacy framework. FERPA and COPPA compliant. Student data protection is a core organizational value.",
    accessibility_notes: "Strong accessibility. Khan Academy platform has robust accessibility features. WCAG compliance inherited from the parent platform.",
    admin_integration_notes: "District dashboard through Khan Academy for Schools. Student progress reporting integrated.",
    editorial_verdict: "A thoughtfully designed AI tutor backed by one of education's most trusted organizations. Best for districts already invested in the Khan Academy ecosystem.",
    categories: ["Tutoring", "Student Support"],
    grade_bands: ["3-5", "6-8", "9-12"],
    audiences: ["Teachers", "Students"],
    pricing_type: "Paid",
    pricing_details: "District pricing through Khan Academy for Districts. Per-student licensing.",
    privacy_level: "High",
    accessibility_level: "Strong",
    scores: { ease_of_use: 8, instructional_value: 9, data_privacy: 9, accessibility: 8 },
    overall_score: 8.6,
    tags: ["tutoring", "math", "Socratic", "Khan Academy", "student-facing", "safe AI"],
    integrations: ["Khan Academy", "Google Classroom", "Clever"],
    compliance_signals: [
      { label: "FERPA Compliant", status: "available", url: "https://www.magicschool.ai/privacy" },
      { label: "COPPA Compliant", status: "available", url: "https://www.magicschool.ai/privacy" },
      { label: "SOC 2 Type II", status: "available", url: "https://www.magicschool.ai/privacy" },
      { label: "DPA Available", status: "available", url: "https://www.magicschool.ai/privacy" },
      { label: "VPAT/ACR", status: "available", url: "https://www.khanacademy.org/about/accessibility-statement" },
    ],
    last_reviewed: "2026-02-20",
    reviewer_notes: "Strong pedagogical foundation. Top marks for privacy. Ecosystem-dependent.",
        vpat_status: "on_request" as const, vpat_url: "https://www.khanacademy.org/about/accessibility-statement", vpat_notes: "Khan Academy publishes an accessibility statement. Full VPAT available by contacting accessibility team.",
listing_tier: "verified", is_featured: true, featured_rank: 2, is_sponsored: false, status: "published",
    similar_tools: ["schoolai", "socratic"],
  },
  {
    id: "3", slug: "brisk-teaching", name: "Brisk Teaching", vendor: "Brisk Labs",
    website: "https://briskteaching.com", affiliate_url: "https://briskteaching.com?ref=dai",
    logo_url: "/logos/brisk.svg",
    description: "Chrome extension that brings AI-powered feedback and grading directly into the tools teachers already use — Google Docs, Slides, Forms, and more.",
    overview: "Brisk is an AI Chrome extension that works inside Google Workspace. Instead of switching to a new platform, teachers can generate lesson plans, quizzes, feedback, and rubrics right inside their existing documents and slides.",
    why_it_matters: "Speeds up feedback cycles dramatically.",
    best_for: ["In-context AI assistance", "Google Workspace users", "Feedback writing", "Grading acceleration"],
    not_ideal_for: ["Non-Google environments", "Student-facing AI", "District-wide analytics"],
    key_features: ["Chrome extension", "Works in Google Docs/Slides/Forms", "AI feedback on student work", "Quiz creation", "Lesson plan generation"],
    instructional_fit: "Reduces friction by meeting teachers where they already work. Particularly effective for feedback and grading workflows.",
    implementation_notes: "Chrome extension installation only. No complex deployment. Works immediately in Google Workspace.",
    privacy_notes: "Medium privacy. FERPA compliant. Data processed through secure channels. Does not store student work permanently.",
    accessibility_notes: "Moderate accessibility. Inherits Google Workspace accessibility features. Extension interface is keyboard-navigable.",
    admin_integration_notes: "Chrome extension can be pushed through Google Admin Console. District licensing available.",
    editorial_verdict: "The best AI tool for teachers who live in Google Workspace. Minimal learning curve and maximum convenience for feedback workflows.",
    categories: ["Feedback & Grading"],
    grade_bands: ["K-2", "3-5", "6-8", "9-12"],
    audiences: ["Teachers"],
    pricing_type: "Freemium",
    pricing_details: "Free tier available. Premium features at $9/mo per teacher. District pricing on request.",
    privacy_level: "Medium",
    accessibility_level: "Moderate",
    scores: { ease_of_use: 9, instructional_value: 8, data_privacy: 6, accessibility: 7 },
    overall_score: 8.0,
    tags: ["chrome extension", "google workspace", "feedback", "grading", "lesson planning"],
    integrations: ["Google Docs", "Google Slides", "Google Forms", "Google Classroom"],
    compliance_signals: [
      { label: "FERPA Compliant", status: "available", url: "https://www.magicschool.ai/privacy" },
      { label: "COPPA Compliant", status: "available", url: "https://www.magicschool.ai/privacy" },
      { label: "DPA Available", status: "available", url: "https://www.magicschool.ai/privacy" },
    ],
    last_reviewed: "2026-03-05",
    reviewer_notes: "Innovative approach. Best for Google-heavy districts.",
        vpat_status: "not_available" as const, vpat_url: null, vpat_notes: "No public VPAT/ACR found. Contact vendor for accessibility documentation.",
listing_tier: "featured", is_featured: true, featured_rank: 5, is_sponsored: false, status: "published",
    similar_tools: ["magicschool-ai", "eduaide-ai"],
  },
  {
    id: "4", slug: "diffit", name: "Diffit", vendor: "Diffit Inc.",
    website: "https://diffit.me", affiliate_url: "https://diffit.me?ref=dai",
    logo_url: "/logos/diffit.svg",
    description: "AI-powered differentiation tool that adapts reading materials and generates resources at any grade level — one of the best tools for scaffolding content.",
    overview: "Diffit specializes in making differentiation effortless. Teachers can input any topic or text, and Diffit generates adapted reading passages, vocabulary lists, comprehension questions, and more at the appropriate reading level.",
    why_it_matters: "One of the best tools for scaffolding content.",
    best_for: ["Reading differentiation", "ELL support", "Vocabulary building", "Adapted assessments", "Scaffolding"],
    not_ideal_for: ["Math instruction", "Open-ended creative projects", "Video content"],
    key_features: ["Text leveling by grade", "Vocabulary generation", "Comprehension questions", "Translation support", "Summary generation"],
    instructional_fit: "Exceptional for supporting diverse learners. Particularly valuable for ELL classrooms and inclusive settings.",
    implementation_notes: "Simple web tool. Google SSO supported. No IT configuration required.",
    privacy_notes: "Medium privacy. FERPA and COPPA compliant. Minimal data collection. Clear privacy policy.",
    accessibility_notes: "Moderate accessibility. Clean, accessible interface. Generated content supports multiple reading levels and languages.",
    admin_integration_notes: "District licensing available. Integration with Google Classroom.",
    editorial_verdict: "Best-in-class differentiation tool. Simple, focused, and highly effective. A must-have for any district prioritizing equitable access to content.",
    categories: ["Differentiation"],
    grade_bands: ["K-2", "3-5", "6-8", "9-12"],
    audiences: ["Teachers", "Instructional Coaches"],
    pricing_type: "Freemium",
    pricing_details: "Free for individual teachers. District plans available for enhanced features.",
    privacy_level: "Medium",
    accessibility_level: "Moderate",
    scores: { ease_of_use: 9, instructional_value: 9, data_privacy: 7, accessibility: 7 },
    overall_score: 8.5,
    tags: ["differentiation", "reading", "ELL", "accessibility", "vocabulary", "scaffolding"],
    integrations: ["Google Classroom"],
    compliance_signals: [
      { label: "FERPA Compliant", status: "available", url: "https://www.magicschool.ai/privacy" },
      { label: "COPPA Compliant", status: "available", url: "https://www.magicschool.ai/privacy" },
      { label: "DPA Available", status: "available", url: "https://www.magicschool.ai/privacy" },
    ],
    last_reviewed: "2026-02-28",
    reviewer_notes: "Excellent tool for differentiation. Strong privacy posture for its category.",
        vpat_status: "not_available" as const, vpat_url: null, vpat_notes: "No public VPAT/ACR found. Contact vendor for accessibility documentation.",
listing_tier: "verified", is_featured: true, featured_rank: 3, is_sponsored: false, status: "published",
    similar_tools: ["magicschool-ai", "eduaide-ai", "twee"],
  },
  {
    id: "5", slug: "curipod", name: "Curipod", vendor: "Curipod AS",
    website: "https://curipod.com", affiliate_url: "https://curipod.com?ref=dai",
    logo_url: "/logos/curipod.svg",
    description: "AI-powered interactive lesson platform with real-time student engagement, polls, and AI-generated slides that turn lessons into interactive experiences quickly.",
    overview: "Curipod combines AI lesson generation with live classroom interaction. Teachers can generate complete interactive lessons in minutes, including polls, open-ended questions, word clouds, and drawing activities.",
    why_it_matters: "Turns lessons into interactive experiences quickly.",
    best_for: ["Interactive lessons", "Student engagement", "Formative assessment", "Classroom discussions"],
    not_ideal_for: ["Asynchronous learning", "Deep content differentiation", "Administrative workflows"],
    key_features: ["AI lesson generator", "Live polls and word clouds", "Drawing activities", "AI feedback on student responses", "Slide-based presentation"],
    instructional_fit: "Ideal for engaging whole-class instruction. Supports formative assessment through real-time responses.",
    implementation_notes: "Browser-based for teachers and students. No app download needed. Google and Microsoft SSO available.",
    privacy_notes: "Medium privacy. GDPR compliant (Norwegian company). FERPA compliant for US districts.",
    accessibility_notes: "Moderate accessibility. Mobile-responsive student interface. Some interactive elements may need adaptation for screen readers.",
    admin_integration_notes: "School and district plans available. Teacher analytics dashboard included.",
    editorial_verdict: "A standout tool for making AI-powered instruction interactive and engaging. Best for districts that value student participation.",
    categories: ["Engagement"],
    grade_bands: ["K-2", "3-5", "6-8", "9-12"],
    audiences: ["Teachers", "Students"],
    pricing_type: "Freemium",
    pricing_details: "Free tier with 3 lessons/mo. Premium at $7.50/mo. School pricing available.",
    privacy_level: "Medium",
    accessibility_level: "Moderate",
    scores: { ease_of_use: 8, instructional_value: 8, data_privacy: 6, accessibility: 7 },
    overall_score: 7.8,
    tags: ["engagement", "interactive", "formative assessment", "presentation", "polls"],
    integrations: ["Google Classroom", "Microsoft Teams"],
    compliance_signals: [
      { label: "FERPA Compliant", status: "available", url: "https://www.magicschool.ai/privacy" },
      { label: "COPPA Compliant", status: "available", url: "https://www.magicschool.ai/privacy" },
      { label: "GDPR Compliant", status: "available", url: "https://curipod.com/privacy-policy" },
      { label: "DPA Available", status: "available", url: "https://www.magicschool.ai/privacy" },
    ],
    last_reviewed: "2026-03-01",
    reviewer_notes: "Engaging product with solid privacy practices.",
        vpat_status: "not_available" as const, vpat_url: null, vpat_notes: "No public VPAT/ACR found. Contact vendor for accessibility documentation.",
listing_tier: "basic", is_featured: false, featured_rank: null, is_sponsored: false, status: "published",
    similar_tools: ["nearpod", "classpoint-ai"],
  },
  {
    id: "6", slug: "eduaide-ai", name: "Eduaide.AI", vendor: "Eduaide",
    website: "https://eduaide.ai", affiliate_url: "https://eduaide.ai?ref=dai",
    logo_url: "/logos/eduaide.svg",
    description: "AI teaching assistant with 100+ resource generators for lesson planning — strong structured outputs aligned to standards.",
    overview: "Eduaide.AI offers a comprehensive suite of AI-powered generators for educational content. With over 100 tools spanning lesson plans, assessments, feedback, and more, it streamlines teacher workflows significantly.",
    why_it_matters: "Strong structured outputs aligned to standards.",
    best_for: ["Resource generation", "Assessment design", "Feedback writing", "Curriculum alignment"],
    not_ideal_for: ["Student-facing activities", "Live classroom use", "Video creation"],
    key_features: ["100+ content generators", "Standards alignment", "Multi-language support", "Feedback assistant", "Lesson hooks generator"],
    instructional_fit: "Strong standards alignment capabilities. Supports backward design and can generate content aligned to state and Common Core standards.",
    implementation_notes: "Browser-based, no installation required. Supports SSO. Minimal training needed.",
    privacy_notes: "Medium privacy. FERPA compliant. Does not store student PII. Clear data handling practices.",
    accessibility_notes: "Moderate accessibility. Web-accessible interface. Output can be modified for accessibility needs.",
    admin_integration_notes: "District licensing available. Admin reporting dashboard in development.",
    editorial_verdict: "A strong contender for districts looking for breadth in AI-generated educational content.",
    categories: ["Lesson Planning"],
    grade_bands: ["K-2", "3-5", "6-8", "9-12"],
    audiences: ["Teachers", "Curriculum Leaders"],
    pricing_type: "Freemium",
    pricing_details: "Free tier with daily limits. Pro plan at $7.99/mo. District pricing on request.",
    privacy_level: "Medium", accessibility_level: "Moderate",
    scores: { ease_of_use: 9, instructional_value: 9, data_privacy: 7, accessibility: 7 },
    overall_score: 8.2,
    tags: ["lesson planning", "assessment", "content generation", "standards alignment"],
    integrations: ["Google Classroom"],
    compliance_signals: [{ label: "FERPA Compliant", status: "available", url: "https://www.magicschool.ai/privacy" }, { label: "COPPA Compliant", status: "available", url: "https://www.magicschool.ai/privacy" }, { label: "DPA Available", status: "available", url: "https://www.magicschool.ai/privacy" }],
    last_reviewed: "2026-03-10", reviewer_notes: "Solid product with rapid feature development.",
        vpat_status: "not_available" as const, vpat_url: null, vpat_notes: "No public VPAT/ACR found. Contact vendor for accessibility documentation.",
listing_tier: "featured", is_featured: false, featured_rank: null, is_sponsored: false, status: "published",
    similar_tools: ["magicschool-ai", "diffit"],
  },
  {
    id: "7", slug: "schoolai", name: "SchoolAI", vendor: "SchoolAI Inc.",
    website: "https://schoolai.com", affiliate_url: "https://schoolai.com?ref=dai",
    logo_url: "/logos/schoolai.svg",
    description: "AI platform for creating safe, teacher-controlled AI spaces where students can interact with AI tutors under monitored guardrails.",
    overview: "SchoolAI allows teachers to create customized AI learning spaces with teacher-controlled guardrails. Teachers can monitor all student conversations in real-time and set topic boundaries.",
    why_it_matters: "Safe AI spaces for student interaction.",
    best_for: ["Student-facing AI", "Custom AI tutors", "Monitored AI interactions", "Differentiated practice"],
    not_ideal_for: ["Lesson planning", "Administrative tasks", "Assessment creation"],
    key_features: ["Custom AI spaces", "Real-time conversation monitoring", "Teacher guardrails", "Topic boundaries", "Student analytics"],
    instructional_fit: "Unique in offering safe, monitored student-AI interaction. Teachers maintain full control.",
    implementation_notes: "Web-based. Student access via join codes. Google and Clever SSO.",
    privacy_notes: "Medium privacy. FERPA and COPPA compliant. All student conversations monitored and reviewable.",
    accessibility_notes: "Moderate accessibility. Text-based interface is screen reader compatible.",
    admin_integration_notes: "School and district plans include admin dashboards.",
    editorial_verdict: "The leading platform for districts that want students to interact with AI safely. Unmatched monitoring capabilities.",
    categories: ["Student Interaction"],
    grade_bands: ["6-8", "9-12"],
    audiences: ["Teachers", "Students", "Administrators"],
    pricing_type: "Freemium",
    pricing_details: "Free tier with limited spaces. Premium at $15/mo per teacher.",
    privacy_level: "Medium", accessibility_level: "Moderate",
    scores: { ease_of_use: 8, instructional_value: 9, data_privacy: 7, accessibility: 7 },
    overall_score: 8.1,
    tags: ["student-facing", "AI tutoring", "guardrails", "monitoring", "safe AI"],
    integrations: ["Google Classroom", "Clever", "Canvas"],
    compliance_signals: [{ label: "FERPA Compliant", status: "available", url: "https://www.magicschool.ai/privacy" }, { label: "COPPA Compliant", status: "available", url: "https://www.magicschool.ai/privacy" }, { label: "SOC 2 Type II", status: "available", url: "https://www.magicschool.ai/privacy" }, { label: "DPA Available", status: "available", url: "https://www.magicschool.ai/privacy" }],
    last_reviewed: "2026-03-12", reviewer_notes: "Best-in-class for monitored student AI.",
        vpat_status: "not_available" as const, vpat_url: null, vpat_notes: "No public VPAT/ACR found. Contact vendor for accessibility documentation.",
listing_tier: "verified", is_featured: true, featured_rank: 4, is_sponsored: false, status: "published",
    similar_tools: ["khanmigo", "socratic"],
  },
  {
    id: "8", slug: "canva", name: "Canva", vendor: "Canva",
    website: "https://canva.com/education", affiliate_url: "https://canva.com/education?ref=dai",
    logo_url: "/logos/canva.svg",
    description: "Universal design platform for visual learning and teacher content creation, free for K–12 educators with AI-powered features.",
    overview: "Canva for Education provides a full design suite free for K–12 teachers and students. AI features include Magic Write, text-to-image generation, and design suggestions.",
    why_it_matters: "Universal tool for visual learning and teacher content.",
    best_for: ["Visual content creation", "Student projects", "Presentations", "Infographics", "Worksheets"],
    not_ideal_for: ["Lesson planning workflows", "Assessment generation", "AI tutoring"],
    key_features: ["Magic Write AI", "Text-to-image", "Template library", "Real-time collaboration", "Brand Kit for schools"],
    instructional_fit: "Supports visual learning and creative expression. Excellent for project-based learning.",
    implementation_notes: "Free for verified educators. Google and Microsoft SSO. LMS integration available.",
    privacy_notes: "Medium privacy. FERPA and COPPA compliant. AI features can be toggled by administrators.",
    accessibility_notes: "Strong accessibility. WCAG 2.1 AA compliant. Screen reader support. Keyboard navigation throughout.",
    admin_integration_notes: "District-wide deployment through Canva for Districts. Admin controls for AI features.",
    editorial_verdict: "An essential creative tool for any district. Free pricing and strong accessibility make it an easy adoption.",
    categories: ["Content Creation"],
    grade_bands: ["K-2", "3-5", "6-8", "9-12"],
    audiences: ["Teachers", "Students"],
    pricing_type: "Freemium",
    pricing_details: "100% free for verified K–12 educators and their students.",
    privacy_level: "Medium", accessibility_level: "Strong",
    scores: { ease_of_use: 9, instructional_value: 9, data_privacy: 7, accessibility: 8 },
    overall_score: 8.3,
    tags: ["design", "visual", "presentations", "creative", "collaboration"],
    integrations: ["Google Classroom", "Microsoft Teams", "Canvas", "Schoology"],
    compliance_signals: [{ label: "FERPA Compliant", status: "available", url: "https://www.magicschool.ai/privacy" }, { label: "COPPA Compliant", status: "available", url: "https://www.magicschool.ai/privacy" }, { label: "SOC 2 Type II", status: "available", url: "https://www.magicschool.ai/privacy" }, { label: "DPA Available", status: "available", url: "https://www.magicschool.ai/privacy" }, { label: "VPAT/ACR", status: "available", url: "https://www.khanacademy.org/about/accessibility-statement" }],
    last_reviewed: "2026-03-08", reviewer_notes: "Excellent free offering with strong safety controls.",
        vpat_status: "available" as const, vpat_url: "https://content-management-files.canva.com/307e4321-765b-4997-bfea-a5f9afd0be13/ACR-Canva-WebApp-Oct-2023.pdf", vpat_notes: "Canva publishes ACR based on VPAT 2.4. WCAG Edition available. Updated annually. Contact accessibility@canva.com for latest version.",
listing_tier: "verified", is_featured: true, featured_rank: 6, is_sponsored: false, status: "published",
    similar_tools: ["adobe-express", "slidesai"],
  },
  {
    id: "9", slug: "adobe-express", name: "Adobe Express", vendor: "Adobe",
    website: "https://adobe.com/education/express", affiliate_url: "https://adobe.com/education/express?ref=dai",
    logo_url: "/logos/adobe.svg",
    description: "Strong district-friendly creative platform with AI-powered features, free for K–12 schools with enterprise-grade privacy.",
    overview: "Adobe Express for Education brings professional-grade creative tools to K–12 classrooms with AI features like Firefly generative AI and student safety controls.",
    why_it_matters: "Strong district-friendly creative platform.",
    best_for: ["Creative projects", "Visual design", "Video creation", "Digital storytelling"],
    not_ideal_for: ["Lesson planning", "Assessment", "AI tutoring"],
    key_features: ["Firefly AI generation", "Video creation", "Template library", "Brand Kit", "Student safety controls"],
    instructional_fit: "Supports creative expression and project-based learning with professional tools.",
    implementation_notes: "Free for K–12 schools. Federated ID and SSO support. Admin console for deployment.",
    privacy_notes: "High privacy — enterprise backing. FERPA and COPPA compliant. AI features age-gated. Adobe's established security framework.",
    accessibility_notes: "Strong accessibility. Adobe's accessibility standards. VPAT available. Keyboard navigation supported.",
    admin_integration_notes: "Adobe Admin Console for deployment. SSO integration. AI feature controls.",
    editorial_verdict: "A premium creative platform with enterprise-grade privacy. Strong alternative to Canva with Adobe's design ecosystem.",
    categories: ["Content Creation"],
    grade_bands: ["K-2", "3-5", "6-8", "9-12"],
    audiences: ["Teachers", "Students"],
    pricing_type: "Freemium",
    pricing_details: "Free for K–12 schools and districts.",
    privacy_level: "High", accessibility_level: "Strong",
    scores: { ease_of_use: 8, instructional_value: 9, data_privacy: 9, accessibility: 8 },
    overall_score: 8.4,
    tags: ["design", "creative", "video", "AI generation", "Adobe"],
    integrations: ["Google Classroom", "Canvas", "Schoology", "Microsoft Teams"],
    compliance_signals: [{ label: "FERPA Compliant", status: "available", url: "https://www.magicschool.ai/privacy" }, { label: "COPPA Compliant", status: "available", url: "https://www.magicschool.ai/privacy" }, { label: "SOC 2 Type II", status: "available", url: "https://www.magicschool.ai/privacy" }, { label: "DPA Available", status: "available", url: "https://www.magicschool.ai/privacy" }, { label: "VPAT/ACR", status: "available", url: "https://www.khanacademy.org/about/accessibility-statement" }],
    last_reviewed: "2026-02-18", reviewer_notes: "Strong enterprise-backed offering for education.",
        vpat_status: "available" as const, vpat_url: "https://www.adobe.com/accessibility/compliance/adobe-express-webapp-2023-acr.html", vpat_notes: "Adobe publishes comprehensive ACRs for all products including Express Web, iOS, and Android. Section 508, WCAG 2.2 AA, and EN 301 549 covered.",
listing_tier: "featured", is_featured: false, featured_rank: null, is_sponsored: false, status: "published",
    similar_tools: ["canva", "slidesai", "pictory"],
  },
  {
    id: "10", slug: "chatgpt", name: "ChatGPT", vendor: "OpenAI",
    website: "https://openai.com/chatgpt", affiliate_url: "https://openai.com/chatgpt?ref=dai",
    logo_url: "/logos/chatgpt.svg",
    description: "The most flexible general-purpose AI tool available — requires guardrails for educational settings but offers unmatched versatility.",
    overview: "ChatGPT offers powerful general-purpose AI capabilities. OpenAI has introduced education-specific features including custom GPTs and team workspaces, but it remains a general tool that requires educator judgment for safe classroom use.",
    why_it_matters: "Most flexible AI tool; requires guardrails.",
    best_for: ["General AI assistance", "Brainstorming", "Content drafting", "Custom GPT creation"],
    not_ideal_for: ["Unmonitored student use", "District-managed deployment", "Younger students"],
    key_features: ["Conversational AI", "Custom GPTs", "Image generation", "Code interpreter", "File analysis", "Team workspaces"],
    instructional_fit: "Extremely versatile but requires teacher judgment. Best as a teacher productivity tool rather than a student-facing platform.",
    implementation_notes: "Requires individual or team accounts. No district SSO or rostering. Teachers need usage guidelines.",
    privacy_notes: "Medium privacy. Enterprise and Team plans offer data protections. Free/Plus plans may use data for training. Districts should negotiate enterprise terms.",
    accessibility_notes: "Strong accessibility. Web interface is generally accessible. Mobile apps available.",
    admin_integration_notes: "Team and Enterprise plans offer admin controls. No LMS integration. Limited district management.",
    editorial_verdict: "The most powerful general-purpose AI available, but lacks education-specific guardrails and admin features. Best positioned as a teacher productivity tool with clear usage guidelines.",
    categories: ["General AI"],
    grade_bands: ["6-8", "9-12"],
    audiences: ["Teachers", "Administrators"],
    pricing_type: "Freemium",
    pricing_details: "Free tier available. Plus at $20/mo. Team at $25/user/mo.",
    privacy_level: "Medium", accessibility_level: "Strong",
    scores: { ease_of_use: 9, instructional_value: 9, data_privacy: 7, accessibility: 8 },
    overall_score: 8.5,
    tags: ["general AI", "chatbot", "content creation", "brainstorming", "GPT"],
    integrations: [],
    compliance_signals: [{ label: "FERPA Compliant", status: "partial", url: "https://www.magicschool.ai/privacy" }, { label: "COPPA Compliant", status: "unavailable", url: "https://www.magicschool.ai/privacy" }, { label: "SOC 2 Type II", status: "available", url: "https://www.magicschool.ai/privacy" }],
    last_reviewed: "2026-03-20", reviewer_notes: "Powerful tool. Privacy and student safety require district guardrails.",
        vpat_status: "not_available" as const, vpat_url: null, vpat_notes: "OpenAI has not published a VPAT/ACR for ChatGPT as of last review. Contact vendor for accessibility documentation.",
listing_tier: "basic", is_featured: false, featured_rank: null, is_sponsored: false, status: "published",
    similar_tools: ["gemini"],
  },
  {
    id: "11", slug: "gemini", name: "Gemini", vendor: "Google",
    website: "https://gemini.google.com", affiliate_url: "https://gemini.google.com?ref=dai",
    logo_url: "/logos/gemini.svg",
    description: "Google's AI assistant that integrates naturally with Google Workspace — the smart choice for Google-heavy schools.",
    overview: "Gemini for Education brings Google's AI directly into Google Workspace for Education. Teachers and students can access AI within Docs, Slides, Sheets, and Gmail with admin controls.",
    why_it_matters: "Integrates well with Google Workspace schools.",
    best_for: ["Google Workspace integration", "Writing assistance", "Research help", "Productivity"],
    not_ideal_for: ["Specialized lesson planning", "Assessment creation", "Non-Google environments"],
    key_features: ["Integrated in Google Docs", "Help Me Write", "Image generation in Slides", "Research assistance", "Admin controls"],
    instructional_fit: "Natural integration with Google Workspace makes it seamless for Google-heavy schools.",
    implementation_notes: "Available through Google Workspace for Education Plus. Enabled through Admin Console.",
    privacy_notes: "Medium privacy. Inherits Google Workspace for Education protections. Data not used for advertising.",
    accessibility_notes: "Strong accessibility. Inherits Google Workspace accessibility features.",
    admin_integration_notes: "Full admin control through Google Admin Console. Age-gating available.",
    editorial_verdict: "The natural choice for Google Workspace districts. Excellent admin controls. Limited as a standalone education AI tool.",
    categories: ["General AI"],
    grade_bands: ["6-8", "9-12"],
    audiences: ["Teachers", "Students", "Administrators"],
    pricing_type: "Freemium",
    pricing_details: "Included with Google Workspace for Education Plus.",
    privacy_level: "Medium", accessibility_level: "Strong",
    scores: { ease_of_use: 8, instructional_value: 9, data_privacy: 7, accessibility: 8 },
    overall_score: 8.3,
    tags: ["Google", "workspace integration", "writing", "productivity"],
    integrations: ["Google Workspace", "Google Classroom", "Google Docs", "Google Slides"],
    compliance_signals: [{ label: "FERPA Compliant", status: "available", url: "https://www.magicschool.ai/privacy" }, { label: "COPPA Compliant", status: "available", url: "https://www.magicschool.ai/privacy" }, { label: "SOC 2 Type II", status: "available", url: "https://www.magicschool.ai/privacy" }, { label: "DPA Available", status: "available", url: "https://www.magicschool.ai/privacy" }, { label: "VPAT/ACR", status: "available", url: "https://www.khanacademy.org/about/accessibility-statement" }],
    last_reviewed: "2026-03-14", reviewer_notes: "Strong integration and admin controls.",
        vpat_status: "available" as const, vpat_url: "https://services.google.com/fh/files/misc/google_gemini_in_workspace_vpat.pdf", vpat_notes: "Google publishes ACR for Gemini in Workspace based on VPAT 2.5. WCAG-EM methodology. Full ACR hub at belonging.google/accessibility-conformance-reports.",
listing_tier: "featured", is_featured: false, featured_rank: null, is_sponsored: false, status: "published",
    similar_tools: ["chatgpt"],
  },
  {
    id: "12", slug: "quizizz-ai", name: "Quizizz AI", vendor: "Quizizz",
    website: "https://quizizz.com", affiliate_url: "https://quizizz.com?ref=dai",
    logo_url: "/logos/quizizz.svg",
    description: "AI-powered quiz and assessment platform that makes fast quiz generation engaging and gamified for K–12 classrooms.",
    overview: "Quizizz uses AI to help teachers generate quizzes, lessons, and interactive activities quickly. Gamification elements keep students engaged while teachers get real-time analytics.",
    why_it_matters: "Fast quiz generation and engagement.",
    best_for: ["Quiz generation", "Gamified assessment", "Formative checks", "Student engagement"],
    not_ideal_for: ["Deep lesson planning", "Writing feedback", "Administrative tasks"],
    key_features: ["AI quiz generator", "Gamification", "Real-time analytics", "Adaptive questions", "LMS integration"],
    instructional_fit: "Excellent for quick formative assessment and review. Gamification drives student participation.",
    implementation_notes: "Web-based. Easy teacher and student sign-up. LMS integrations available.",
    privacy_notes: "Medium privacy. FERPA compliant. Student data handling documented.",
    accessibility_notes: "Moderate accessibility. Gamified interface may present challenges for some assistive technologies.",
    admin_integration_notes: "School and district plans available. Admin dashboard for usage tracking.",
    editorial_verdict: "A strong gamified assessment tool with useful AI-powered quiz generation. Popular with students and teachers alike.",
    categories: ["Assessment"],
    grade_bands: ["K-2", "3-5", "6-8", "9-12"],
    audiences: ["Teachers", "Students"],
    pricing_type: "Freemium",
    pricing_details: "Free tier available. School plans with additional features.",
    privacy_level: "Medium", accessibility_level: "Moderate",
    scores: { ease_of_use: 9, instructional_value: 8, data_privacy: 7, accessibility: 7 },
    overall_score: 8.1,
    tags: ["quiz", "gamification", "assessment", "engagement", "formative"],
    integrations: ["Google Classroom", "Canvas", "Schoology"],
    compliance_signals: [{ label: "FERPA Compliant", status: "available", url: "https://www.magicschool.ai/privacy" }, { label: "COPPA Compliant", status: "available", url: "https://www.magicschool.ai/privacy" }, { label: "DPA Available", status: "available", url: "https://www.magicschool.ai/privacy" }],
    last_reviewed: "2026-03-02", reviewer_notes: "Popular and effective. Gamification is well-implemented.",
        vpat_status: "not_available" as const, vpat_url: null, vpat_notes: "No public VPAT/ACR found. Contact vendor for accessibility documentation.",
listing_tier: "basic", is_featured: false, featured_rank: null, is_sponsored: false, status: "published",
    similar_tools: ["classpoint-ai", "formative", "quizlet"],
  },
  {
    id: "13", slug: "quizlet", name: "Quizlet", vendor: "Quizlet Inc.",
    website: "https://quizlet.com", affiliate_url: "https://quizlet.com?ref=dai",
    logo_url: "/logos/quizlet.svg",
    description: "AI-enhanced study platform with flashcards, practice tests, and Q-Chat AI tutor — widely adopted and familiar to students.",
    overview: "Quizlet is one of the most widely-used study platforms, now enhanced with AI features including Q-Chat, an AI tutor that uses Socratic dialogue.",
    why_it_matters: "Widely adopted and familiar to students.",
    best_for: ["Study and review", "Vocabulary building", "Test preparation", "Spaced repetition"],
    not_ideal_for: ["Lesson planning", "Creative projects", "Open-ended learning"],
    key_features: ["Q-Chat AI tutor", "Flashcard generation", "Practice tests", "Learn mode", "Spaced repetition"],
    instructional_fit: "Excellent for review and retrieval practice. Best as a supplementary study tool.",
    implementation_notes: "Student and teacher accounts available. Google SSO. No complex IT deployment.",
    privacy_notes: "Medium privacy. FERPA and COPPA compliant for school accounts.",
    accessibility_notes: "Strong accessibility. Mobile and web accessible. Audio features for language learning.",
    admin_integration_notes: "School plans available. Teacher can manage classes.",
    editorial_verdict: "A beloved study tool now enhanced with thoughtful AI features. Best as a complementary tool in any district's toolkit.",
    categories: ["Study Tools"],
    grade_bands: ["K-2", "3-5", "6-8", "9-12"],
    audiences: ["Teachers", "Students"],
    pricing_type: "Freemium",
    pricing_details: "Free tier for basic features. Plus at $7.99/mo.",
    privacy_level: "Medium", accessibility_level: "Strong",
    scores: { ease_of_use: 8, instructional_value: 8, data_privacy: 7, accessibility: 8 },
    overall_score: 8.0,
    tags: ["flashcards", "study", "review", "AI tutor", "vocabulary"],
    integrations: ["Google Classroom"],
    compliance_signals: [{ label: "FERPA Compliant", status: "available", url: "https://www.magicschool.ai/privacy" }, { label: "COPPA Compliant", status: "available", url: "https://www.magicschool.ai/privacy" }, { label: "DPA Available", status: "available", url: "https://www.magicschool.ai/privacy" }],
    last_reviewed: "2026-02-22", reviewer_notes: "Well-known platform with solid AI additions.",
        vpat_status: "not_available" as const, vpat_url: null, vpat_notes: "No public VPAT/ACR found. Contact vendor for accessibility documentation.",
listing_tier: "basic", is_featured: false, featured_rank: null, is_sponsored: false, status: "published",
    similar_tools: ["quizizz-ai"],
  },
  {
    id: "14", slug: "grammarly", name: "Grammarly", vendor: "Grammarly Inc.",
    website: "https://grammarly.com/edu", affiliate_url: "https://grammarly.com/edu?ref=dai",
    logo_url: "/logos/grammarly.svg",
    description: "AI-powered writing support that improves writing clarity at scale — trusted by millions and now with education-specific features.",
    overview: "Grammarly uses AI to provide real-time writing feedback on grammar, clarity, tone, and style. Education plans offer plagiarism detection and admin controls for schools.",
    why_it_matters: "Improves writing clarity at scale.",
    best_for: ["Writing improvement", "Grammar feedback", "Tone adjustment", "Plagiarism detection"],
    not_ideal_for: ["Lesson planning", "Math instruction", "Younger students", "Creative writing coaching"],
    key_features: ["Real-time writing feedback", "Tone detection", "Plagiarism checker", "Clarity suggestions", "Browser extension"],
    instructional_fit: "Supports writing across all subjects. Helps students develop self-editing skills.",
    implementation_notes: "Browser extension and web app. Education plans include admin dashboard. SSO available.",
    privacy_notes: "Medium privacy. FERPA compliant for education plans. Enterprise-grade security.",
    accessibility_notes: "Strong accessibility. Works across browsers and platforms. Screen reader compatible.",
    admin_integration_notes: "Education admin dashboard. Usage analytics. SSO and provisioning support.",
    editorial_verdict: "A mature, trusted writing tool with genuine AI capabilities. Education plans make it district-appropriate.",
    categories: ["Writing Support"],
    grade_bands: ["6-8", "9-12"],
    audiences: ["Teachers", "Students"],
    pricing_type: "Freemium",
    pricing_details: "Free basic features. Education plans with institutional pricing.",
    privacy_level: "Medium", accessibility_level: "Strong",
    scores: { ease_of_use: 9, instructional_value: 8, data_privacy: 7, accessibility: 8 },
    overall_score: 8.2,
    tags: ["writing", "grammar", "feedback", "plagiarism", "editing"],
    integrations: ["Google Docs", "Microsoft Word", "Canvas"],
    compliance_signals: [{ label: "FERPA Compliant", status: "available", url: "https://www.magicschool.ai/privacy" }, { label: "SOC 2 Type II", status: "available", url: "https://www.magicschool.ai/privacy" }, { label: "DPA Available", status: "available", url: "https://www.magicschool.ai/privacy" }],
    last_reviewed: "2026-03-18", reviewer_notes: "Trusted brand with genuine education value.",
        vpat_status: "not_available" as const, vpat_url: null, vpat_notes: "No public VPAT/ACR found. Contact vendor for accessibility documentation.",
listing_tier: "featured", is_featured: false, featured_rank: null, is_sponsored: true, status: "published",
    similar_tools: ["twee"],
  },
  {
    id: "15", slug: "otter-ai", name: "Otter.ai", vendor: "Otter.ai Inc.",
    website: "https://otter.ai", affiliate_url: "https://otter.ai?ref=dai",
    logo_url: "/logos/otter.svg",
    description: "AI-powered transcription and note-taking that supports accessibility and meeting capture for educators and administrators.",
    overview: "Otter.ai uses AI to transcribe meetings, classes, and conversations in real-time. It supports accessibility by providing text transcripts and searchable notes.",
    why_it_matters: "Supports accessibility and meeting capture.",
    best_for: ["Meeting transcription", "Accessibility support", "Note-taking", "IEP meeting documentation"],
    not_ideal_for: ["Lesson planning", "Student-facing activities", "Assessment creation"],
    key_features: ["Real-time transcription", "Searchable notes", "Speaker identification", "Summary generation", "Meeting integration"],
    instructional_fit: "Valuable for accessibility compliance and administrative documentation. Supports hearing-impaired students.",
    implementation_notes: "Web and mobile apps. Integrates with Zoom, Google Meet, and Microsoft Teams.",
    privacy_notes: "Medium privacy. Enterprise security features. Data handling documented.",
    accessibility_notes: "Strong accessibility. Core purpose is accessibility support. Real-time captions for meetings.",
    admin_integration_notes: "Education plans available. Admin controls for data retention.",
    editorial_verdict: "An essential accessibility tool that doubles as a productivity tool for meetings and note-taking.",
    categories: ["Accessibility & Notes"],
    grade_bands: ["K-2", "3-5", "6-8", "9-12"],
    audiences: ["Teachers", "Administrators"],
    pricing_type: "Freemium",
    pricing_details: "Free tier with limited minutes. Education pricing available.",
    privacy_level: "Medium", accessibility_level: "Strong",
    scores: { ease_of_use: 8, instructional_value: 9, data_privacy: 7, accessibility: 8 },
    overall_score: 8.3,
    tags: ["transcription", "accessibility", "notes", "meetings", "captions"],
    integrations: ["Zoom", "Google Meet", "Microsoft Teams"],
    compliance_signals: [{ label: "FERPA Compliant", status: "partial", url: "https://www.magicschool.ai/privacy" }, { label: "SOC 2 Type II", status: "available", url: "https://www.magicschool.ai/privacy" }],
    last_reviewed: "2026-03-06", reviewer_notes: "Strong accessibility value. Privacy for education use needs deeper verification.",
        vpat_status: "on_request" as const, vpat_url: "https://otter.ai/privacy-security", vpat_notes: "Otter.ai states VPAT completed for Section 508 compliance on their privacy page. Full document available upon request.",
listing_tier: "basic", is_featured: false, featured_rank: null, is_sponsored: false, status: "published",
    similar_tools: [],
  },
  {
    id: "16", slug: "slidesai", name: "SlidesAI", vendor: "SlidesAI",
    website: "https://slidesai.io", affiliate_url: "https://slidesai.io?ref=dai",
    logo_url: "/logos/slidesai.svg",
    description: "AI-powered presentation generator that creates slide decks from text input — useful for quick content creation.",
    overview: "SlidesAI generates Google Slides presentations from text descriptions using AI. Teachers can quickly create presentation materials from lesson notes or outlines.",
    why_it_matters: "Quick AI-generated presentations from text.",
    best_for: ["Presentation creation", "Quick slide generation", "Visual summaries"],
    not_ideal_for: ["Complex lesson design", "Assessment", "Student interaction"],
    key_features: ["Text-to-slides", "Google Slides integration", "Multiple themes", "Summary generation"],
    instructional_fit: "Time-saver for creating presentation materials. Output quality varies and typically needs teacher refinement.",
    implementation_notes: "Google Slides add-on. Simple installation. No IT support needed.",
    privacy_notes: "Medium privacy. Processes text through AI. Limited education-specific privacy documentation.",
    accessibility_notes: "Moderate accessibility. Generated slides may need manual accessibility adjustments.",
    admin_integration_notes: "Individual tool. No admin controls or district management features.",
    editorial_verdict: "A useful time-saver for quick presentations, but output quality requires teacher oversight.",
    categories: ["Content Creation"],
    grade_bands: ["K-2", "3-5", "6-8", "9-12"],
    audiences: ["Teachers"],
    pricing_type: "Freemium",
    pricing_details: "Free tier with limited presentations. Pro plans available.",
    privacy_level: "Medium", accessibility_level: "Moderate",
    scores: { ease_of_use: 8, instructional_value: 8, data_privacy: 7, accessibility: 7 },
    overall_score: 7.9,
    tags: ["presentations", "slides", "content creation", "Google Slides"],
    integrations: ["Google Slides"],
    compliance_signals: [{ label: "FERPA Compliant", status: "unknown", url: "https://www.magicschool.ai/privacy" }],
    last_reviewed: "2026-02-15", reviewer_notes: "Useful but limited. Needs teacher review of outputs.",
        vpat_status: "not_available" as const, vpat_url: null, vpat_notes: "No public VPAT/ACR found. Not an education-specific vendor. Contact vendor for accessibility documentation.",
listing_tier: "basic", is_featured: false, featured_rank: null, is_sponsored: false, status: "published",
    similar_tools: ["canva", "adobe-express"],
  },
  {
    id: "17", slug: "twee", name: "Twee", vendor: "Twee",
    website: "https://twee.com", affiliate_url: "https://twee.com?ref=dai",
    logo_url: "/logos/twee.svg",
    description: "AI-powered ELA and language teaching tool that generates reading passages, questions, and vocabulary exercises aligned to proficiency levels.",
    overview: "Twee uses AI to generate language teaching materials including reading passages, comprehension questions, vocabulary exercises, and dialogue practice at various proficiency levels.",
    why_it_matters: "Strong ELA and language learning content generation.",
    best_for: ["ELA instruction", "ESL/ELL support", "Reading passage generation", "Vocabulary exercises"],
    not_ideal_for: ["Math instruction", "Science labs", "Administrative tasks"],
    key_features: ["Reading passage generator", "Question creation", "Vocabulary exercises", "Dialogue generation", "Level adaptation"],
    instructional_fit: "Well-suited for language arts and ESL instruction. Content is generated at specified proficiency levels.",
    implementation_notes: "Web-based tool. No complex deployment. Individual teacher use.",
    privacy_notes: "Medium privacy. Does not process student data. Teacher-only tool.",
    accessibility_notes: "Moderate accessibility. Clean web interface.",
    admin_integration_notes: "Individual tool. No district management features.",
    editorial_verdict: "A focused, effective tool for ELA and language teachers. Does its niche well.",
    categories: ["ELA & Language"],
    grade_bands: ["6-8", "9-12"],
    audiences: ["Teachers"],
    pricing_type: "Freemium",
    pricing_details: "Free tier with daily limits. Premium plans available.",
    privacy_level: "Medium", accessibility_level: "Moderate",
    scores: { ease_of_use: 8, instructional_value: 9, data_privacy: 7, accessibility: 7 },
    overall_score: 8.0,
    tags: ["ELA", "language", "reading", "vocabulary", "ESL"],
    integrations: [],
    compliance_signals: [{ label: "FERPA Compliant", status: "partial", url: "https://www.magicschool.ai/privacy" }],
    last_reviewed: "2026-02-25", reviewer_notes: "Good niche tool for language instruction.",
        vpat_status: "not_available" as const, vpat_url: null, vpat_notes: "No public VPAT/ACR found. Contact vendor for accessibility documentation.",
listing_tier: "basic", is_featured: false, featured_rank: null, is_sponsored: false, status: "published",
    similar_tools: ["diffit", "eduaide-ai"],
  },
  {
    id: "18", slug: "socratic", name: "Socratic", vendor: "Google",
    website: "https://socratic.org", affiliate_url: "https://socratic.org?ref=dai",
    logo_url: "/logos/socratic.svg",
    description: "Google-backed AI homework helper that explains concepts step-by-step — high privacy and strong accessibility for student use.",
    overview: "Socratic by Google helps students understand homework problems by providing step-by-step explanations. It uses AI to break down questions across subjects and provide educational resources.",
    why_it_matters: "Safe, free, Google-backed student support tool.",
    best_for: ["Homework help", "Concept explanation", "Step-by-step math", "Science questions"],
    not_ideal_for: ["Teacher planning", "Assessment creation", "Creative projects"],
    key_features: ["Photo-based question input", "Step-by-step explanations", "Multiple subjects", "Visual learning aids", "Google integration"],
    instructional_fit: "Good supplementary tool for independent student learning. Encourages understanding over answer-copying.",
    implementation_notes: "Free mobile app. No account required. No IT deployment needed.",
    privacy_notes: "High privacy. Google-backed with strong data protections. No data used for advertising.",
    accessibility_notes: "Strong accessibility. Mobile-optimized. Clean, simple interface.",
    admin_integration_notes: "No admin controls needed. Free individual tool.",
    editorial_verdict: "A trustworthy, free student support tool with Google's privacy infrastructure. Excellent for independent learning.",
    categories: ["Student Support"],
    grade_bands: ["6-8", "9-12"],
    audiences: ["Students"],
    pricing_type: "Free",
    pricing_details: "Completely free. No premium tier.",
    privacy_level: "High", accessibility_level: "Strong",
    scores: { ease_of_use: 9, instructional_value: 8, data_privacy: 9, accessibility: 8 },
    overall_score: 8.4,
    tags: ["homework", "student support", "math", "science", "Google", "free"],
    integrations: [],
    compliance_signals: [{ label: "FERPA Compliant", status: "available", url: "https://www.magicschool.ai/privacy" }, { label: "COPPA Compliant", status: "available", url: "https://www.magicschool.ai/privacy" }],
    last_reviewed: "2026-02-10", reviewer_notes: "Reliable, safe, and free. Limited scope but excellent within it.",
        vpat_status: "on_request" as const, vpat_url: "https://belonging.google/accessibility-conformance-reports/", vpat_notes: "Google product. Check Google Accessibility Conformance Reports hub for latest. Socratic-specific ACR may not be published separately.",
listing_tier: "basic", is_featured: false, featured_rank: null, is_sponsored: false, status: "published",
    similar_tools: ["khanmigo", "schoolai"],
  },
  {
    id: "19", slug: "formative", name: "Formative", vendor: "Formative (GoFormative)",
    website: "https://formative.com", affiliate_url: "https://formative.com?ref=dai",
    logo_url: "/logos/formative.svg",
    description: "Real-time formative assessment platform with AI-powered grading, instant feedback, and intervention tools for data-driven instruction.",
    overview: "Formative enables teachers to create assessments with real-time student response tracking. AI features include auto-grading of open-ended responses and intelligent feedback suggestions.",
    why_it_matters: "Real-time formative assessment with AI grading.",
    best_for: ["Formative assessment", "Real-time monitoring", "AI grading", "Student feedback"],
    not_ideal_for: ["Lesson planning", "Content creation", "Student-facing AI chat"],
    key_features: ["Real-time response tracking", "AI auto-grading", "Show Your Work", "Intervention alerts", "Standards tracking"],
    instructional_fit: "Excellent for assessment-driven instruction. Real-time data allows on-the-fly adjustments.",
    implementation_notes: "Web-based with mobile support. LMS integration. Clever and ClassLink rostering.",
    privacy_notes: "Medium privacy. FERPA and COPPA compliant. District-level data agreements available.",
    accessibility_notes: "Strong accessibility. VPAT available. Keyboard navigation supported.",
    admin_integration_notes: "School and district admin dashboards. Standards-based reporting.",
    editorial_verdict: "A powerful formative assessment tool with genuinely useful AI grading. Best for data-driven instruction.",
    categories: ["Assessment"],
    grade_bands: ["K-2", "3-5", "6-8", "9-12"],
    audiences: ["Teachers", "Students", "Administrators"],
    pricing_type: "Freemium",
    pricing_details: "Free tier with basic features. Premium for schools and districts.",
    privacy_level: "Medium", accessibility_level: "Strong",
    scores: { ease_of_use: 8, instructional_value: 9, data_privacy: 7, accessibility: 8 },
    overall_score: 8.3,
    tags: ["assessment", "formative", "grading", "AI feedback", "real-time"],
    integrations: ["Google Classroom", "Canvas", "Clever", "ClassLink"],
    compliance_signals: [{ label: "FERPA Compliant", status: "available", url: "https://www.magicschool.ai/privacy" }, { label: "COPPA Compliant", status: "available", url: "https://www.magicschool.ai/privacy" }, { label: "DPA Available", status: "available", url: "https://www.magicschool.ai/privacy" }, { label: "VPAT/ACR", status: "available", url: "https://www.khanacademy.org/about/accessibility-statement" }],
    last_reviewed: "2026-02-15", reviewer_notes: "Solid assessment platform with meaningful AI features.",
        vpat_status: "on_request" as const, vpat_url: null, vpat_notes: "VPAT mentioned in vendor documentation. Available upon request from sales team.",
listing_tier: "featured", is_featured: false, featured_rank: null, is_sponsored: false, status: "published",
    similar_tools: ["quizizz-ai", "classpoint-ai", "nearpod"],
  },
  {
    id: "20", slug: "nearpod", name: "Nearpod", vendor: "Renaissance Learning",
    website: "https://nearpod.com", affiliate_url: "https://nearpod.com?ref=dai",
    logo_url: "/logos/nearpod.svg",
    description: "Interactive lesson platform with AI-enhanced content creation, VR experiences, and real-time formative assessment — a classroom engagement powerhouse.",
    overview: "Nearpod combines pre-built lessons, interactive activities, and formative assessments. Recently enhanced with AI features for lesson creation and content adaptation.",
    why_it_matters: "Comprehensive engagement platform with AI enhancements.",
    best_for: ["Interactive lessons", "Virtual field trips", "Formative assessment", "Standards-aligned content"],
    not_ideal_for: ["Open-ended AI conversations", "Administrative workflows", "Deep differentiation"],
    key_features: ["Interactive slides", "Virtual reality experiences", "Gamification", "AI lesson builder", "Real-time assessment"],
    instructional_fit: "Strong instructional design framework. VR experiences add unique immersive learning opportunities.",
    implementation_notes: "Integrates deeply with major LMS platforms. District deployment well-supported.",
    privacy_notes: "Medium privacy. FERPA and COPPA compliant through Renaissance Learning.",
    accessibility_notes: "Strong accessibility. VPAT available. Ongoing accessibility improvements.",
    admin_integration_notes: "Full district administration suite. Rostering through Clever and ClassLink.",
    editorial_verdict: "A mature, well-supported platform for interactive instruction. AI features are evolving but the core platform is rock-solid.",
    categories: ["Engagement"],
    grade_bands: ["K-2", "3-5", "6-8", "9-12"],
    audiences: ["Teachers", "Students", "Administrators"],
    pricing_type: "Freemium",
    pricing_details: "Free tier with limited lessons. School and district pricing through Renaissance.",
    privacy_level: "Medium", accessibility_level: "Strong",
    scores: { ease_of_use: 9, instructional_value: 9, data_privacy: 7, accessibility: 8 },
    overall_score: 8.4,
    tags: ["interactive", "VR", "formative assessment", "engagement", "lesson delivery"],
    integrations: ["Google Classroom", "Canvas", "Schoology", "Clever", "ClassLink"],
    compliance_signals: [{ label: "FERPA Compliant", status: "available", url: "https://www.magicschool.ai/privacy" }, { label: "COPPA Compliant", status: "available", url: "https://www.magicschool.ai/privacy" }, { label: "SOC 2 Type II", status: "available", url: "https://www.magicschool.ai/privacy" }, { label: "DPA Available", status: "available", url: "https://www.magicschool.ai/privacy" }, { label: "VPAT/ACR", status: "available", url: "https://www.khanacademy.org/about/accessibility-statement" }],
    last_reviewed: "2026-02-25", reviewer_notes: "Established platform with growing AI capabilities.",
        vpat_status: "on_request" as const, vpat_url: null, vpat_notes: "Nearpod states VPAT targeting WCAG 2.0 AA is available upon request. Contact Nearpod or Renaissance Learning sales team.",
listing_tier: "verified", is_featured: true, featured_rank: 7, is_sponsored: false, status: "published",
    similar_tools: ["curipod", "formative"],
  },
  {
    id: "21", slug: "classpoint-ai", name: "ClassPoint AI", vendor: "Inknoe",
    website: "https://classpoint.io", affiliate_url: "https://classpoint.io?ref=dai",
    logo_url: "/logos/classpoint.svg",
    description: "AI-powered assessment tool that generates quiz questions directly from PowerPoint slides — seamless for teachers who live in PowerPoint.",
    overview: "ClassPoint AI integrates into Microsoft PowerPoint to generate assessment questions from slide content. Teachers can create quizzes, polls, and interactive activities without leaving their presentations.",
    why_it_matters: "AI assessment generation inside PowerPoint.",
    best_for: ["PowerPoint-based assessment", "Quick quiz generation", "In-slide interaction", "Gamification"],
    not_ideal_for: ["Non-PowerPoint users", "Lesson planning", "Writing feedback"],
    key_features: ["AI question generation from slides", "Gamification stars", "Interactive quizzes", "Leaderboard", "PowerPoint integration"],
    instructional_fit: "Excellent for teachers who present via PowerPoint. Reduces the friction of creating assessments.",
    implementation_notes: "PowerPoint add-in. Simple installation. Works with Microsoft 365.",
    privacy_notes: "Medium privacy. Data processing through Microsoft ecosystem.",
    accessibility_notes: "Moderate accessibility. Inherits PowerPoint's accessibility features.",
    admin_integration_notes: "School plans available. Basic admin features.",
    editorial_verdict: "A smart integration for PowerPoint-heavy teachers. Assessment generation is genuinely useful.",
    categories: ["Assessment"],
    grade_bands: ["K-2", "3-5", "6-8", "9-12"],
    audiences: ["Teachers"],
    pricing_type: "Freemium",
    pricing_details: "Free tier with limited AI generations. Pro plans available.",
    privacy_level: "Medium", accessibility_level: "Moderate",
    scores: { ease_of_use: 8, instructional_value: 9, data_privacy: 7, accessibility: 7 },
    overall_score: 8.0,
    tags: ["PowerPoint", "assessment", "quiz", "gamification", "Microsoft"],
    integrations: ["Microsoft PowerPoint", "Microsoft 365"],
    compliance_signals: [{ label: "FERPA Compliant", status: "partial", url: "https://www.magicschool.ai/privacy" }],
    last_reviewed: "2026-03-04", reviewer_notes: "Good for PowerPoint-centric workflows.",
        vpat_status: "not_available" as const, vpat_url: null, vpat_notes: "No public VPAT/ACR found. Contact Inknoe for accessibility documentation.",
listing_tier: "basic", is_featured: false, featured_rank: null, is_sponsored: false, status: "published",
    similar_tools: ["quizizz-ai", "formative"],
  },
  {
    id: "22", slug: "edpuzzle", name: "Edpuzzle", vendor: "Edpuzzle Inc.",
    website: "https://edpuzzle.com", affiliate_url: "https://edpuzzle.com?ref=dai",
    logo_url: "/logos/edpuzzle.svg",
    description: "AI-enhanced video learning platform that lets teachers embed questions in any video and track student comprehension in real-time.",
    overview: "Edpuzzle allows teachers to take any video and add interactive questions, audio notes, and comments. AI features help generate questions and summaries from video content.",
    why_it_matters: "Makes any video an interactive learning experience.",
    best_for: ["Video-based learning", "Flipped classroom", "Student accountability", "Comprehension checks"],
    not_ideal_for: ["Text-heavy content", "Real-time interaction", "Creative projects"],
    key_features: ["Embed questions in videos", "Student progress tracking", "AI question generation", "Video cropping", "LMS integration"],
    instructional_fit: "Transforms passive video watching into active learning. Strong for flipped classroom models.",
    implementation_notes: "Web-based. Easy LMS integration. Clever and Google SSO.",
    privacy_notes: "Medium privacy. FERPA and COPPA compliant. Student data protections in place.",
    accessibility_notes: "Strong accessibility. Supports captions. Mobile responsive.",
    admin_integration_notes: "School and district plans. Admin dashboard. Rostering support.",
    editorial_verdict: "A well-established video learning platform with thoughtful AI additions. Essential for flipped classroom approaches.",
    categories: ["Video Learning"],
    grade_bands: ["K-2", "3-5", "6-8", "9-12"],
    audiences: ["Teachers", "Students"],
    pricing_type: "Freemium",
    pricing_details: "Free tier for individual teachers. School and district pricing.",
    privacy_level: "Medium", accessibility_level: "Strong",
    scores: { ease_of_use: 9, instructional_value: 9, data_privacy: 7, accessibility: 8 },
    overall_score: 8.3,
    tags: ["video", "flipped classroom", "interactive", "comprehension", "tracking"],
    integrations: ["Google Classroom", "Canvas", "Schoology", "Clever"],
    compliance_signals: [{ label: "FERPA Compliant", status: "available", url: "https://www.magicschool.ai/privacy" }, { label: "COPPA Compliant", status: "available", url: "https://www.magicschool.ai/privacy" }, { label: "DPA Available", status: "available", url: "https://www.magicschool.ai/privacy" }],
    last_reviewed: "2026-03-10", reviewer_notes: "Established and reliable. AI features enhance an already strong platform.",
        vpat_status: "not_available" as const, vpat_url: null, vpat_notes: "No public VPAT/ACR found. Contact vendor for accessibility documentation.",
listing_tier: "featured", is_featured: false, featured_rank: null, is_sponsored: false, status: "published",
    similar_tools: ["nearpod"],
  },
  {
    id: "23", slug: "pictory", name: "Pictory", vendor: "Pictory AI",
    website: "https://pictory.ai", affiliate_url: "https://pictory.ai?ref=dai",
    logo_url: "/logos/pictory.svg",
    description: "AI video creation platform that turns text and articles into short videos — useful for creating visual content from written materials.",
    overview: "Pictory uses AI to convert text content into video summaries. Teachers can turn blog posts, articles, or lesson notes into short video content for students.",
    why_it_matters: "Converts text content into video format with AI.",
    best_for: ["Text-to-video conversion", "Summary videos", "Content repurposing"],
    not_ideal_for: ["Interactive learning", "Assessment", "Student-facing AI", "Live instruction"],
    key_features: ["Text-to-video", "Auto-captioning", "Stock media library", "Script editor", "Brand customization"],
    instructional_fit: "Useful for creating supplementary video content. Quality varies and teacher review is essential.",
    implementation_notes: "Web-based. Individual accounts. No education-specific deployment.",
    privacy_notes: "Medium privacy. General platform, not education-specific. Standard data handling.",
    accessibility_notes: "Moderate accessibility. Auto-captions support accessibility. Web-based interface.",
    admin_integration_notes: "No education admin features. Individual tool use.",
    editorial_verdict: "A useful content creation tool for teachers who want to add video to their materials, but not education-specific.",
    categories: ["Content Creation"],
    grade_bands: ["K-2", "3-5", "6-8", "9-12"],
    audiences: ["Teachers"],
    pricing_type: "Paid",
    pricing_details: "Starter at $19/mo. Professional plans available.",
    privacy_level: "Medium", accessibility_level: "Moderate",
    scores: { ease_of_use: 8, instructional_value: 8, data_privacy: 6, accessibility: 7 },
    overall_score: 7.8,
    tags: ["video creation", "text-to-video", "content", "captions"],
    integrations: [],
    compliance_signals: [],
    last_reviewed: "2026-01-20", reviewer_notes: "Not education-specific. Useful for teacher content creation.",
        vpat_status: "not_available" as const, vpat_url: null, vpat_notes: "No public VPAT/ACR found. Not an education-specific vendor. Contact vendor for accessibility documentation.",
listing_tier: "basic", is_featured: false, featured_rank: null, is_sponsored: false, status: "published",
    similar_tools: ["lumen5", "canva", "adobe-express"],
  },
  {
    id: "24", slug: "lumen5", name: "Lumen5", vendor: "Lumen5",
    website: "https://lumen5.com", affiliate_url: "https://lumen5.com?ref=dai",
    logo_url: "/logos/lumen5.svg",
    description: "AI-powered video creation platform that transforms text content into engaging video presentations — good for repurposing educational content.",
    overview: "Lumen5 uses AI to create videos from text content. Teachers and administrators can turn newsletters, blog posts, and reports into shareable video content.",
    why_it_matters: "Quick video creation from text for education communications.",
    best_for: ["Video summaries", "Communication content", "Newsletter-to-video", "Social media content"],
    not_ideal_for: ["Direct instruction", "Assessment", "Student interaction", "Complex lesson design"],
    key_features: ["Text-to-video", "AI scene generation", "Media library", "Brand templates", "Auto-resizing for platforms"],
    instructional_fit: "Better suited for communication and marketing than direct instruction. Useful for admin-to-community content.",
    implementation_notes: "Web-based platform. Individual accounts.",
    privacy_notes: "Medium privacy. General platform. Not education-specific.",
    accessibility_notes: "Moderate accessibility. Auto-captions available.",
    admin_integration_notes: "No education-specific admin features.",
    editorial_verdict: "More useful for district communications than direct classroom instruction. A nice-to-have, not a must-have.",
    categories: ["Content Creation"],
    grade_bands: ["K-2", "3-5", "6-8", "9-12"],
    audiences: ["Teachers", "Administrators"],
    pricing_type: "Freemium",
    pricing_details: "Free tier with watermark. Starter at $19/mo.",
    privacy_level: "Medium", accessibility_level: "Moderate",
    scores: { ease_of_use: 8, instructional_value: 8, data_privacy: 6, accessibility: 7 },
    overall_score: 7.7,
    tags: ["video creation", "text-to-video", "communications", "marketing"],
    integrations: [],
    compliance_signals: [],
    last_reviewed: "2026-01-15", reviewer_notes: "Better for district comms than classroom use.",
        vpat_status: "not_available" as const, vpat_url: null, vpat_notes: "No public VPAT/ACR found. Not an education-specific vendor. Contact vendor for accessibility documentation.",
listing_tier: "basic", is_featured: false, featured_rank: null, is_sponsored: false, status: "published",
    similar_tools: ["pictory", "canva"],
  },
  {
    id: "25", slug: "notion-ai", name: "Notion AI", vendor: "Notion Labs",
    website: "https://notion.so", affiliate_url: "https://notion.so?ref=dai",
    logo_url: "/logos/notion.svg",
    description: "AI-enhanced productivity workspace powerful for teacher organization, curriculum planning, and workflow management.",
    overview: "Notion AI adds AI capabilities to the Notion workspace platform, enabling teachers to draft content, summarize notes, create templates, and organize complex projects with AI assistance.",
    why_it_matters: "Powerful for teacher organization and workflows.",
    best_for: ["Curriculum planning", "Teacher organization", "Note-taking", "Content drafting", "Workflow management"],
    not_ideal_for: ["Student-facing activities", "Assessment", "Younger students", "Real-time classroom use"],
    key_features: ["AI writing assistant", "Database organization", "Template generation", "Summary creation", "Project management"],
    instructional_fit: "Strong for teacher productivity and planning. Not designed for direct student interaction.",
    implementation_notes: "Web and desktop app. Individual or team accounts.",
    privacy_notes: "Medium privacy. Enterprise features available for organizations. SOC 2 compliant.",
    accessibility_notes: "Moderate accessibility. Keyboard navigation supported. Some accessibility gaps in complex views.",
    admin_integration_notes: "Team and enterprise plans include admin controls.",
    editorial_verdict: "A power tool for organized teachers and curriculum teams. The AI features enhance an already excellent productivity platform.",
    categories: ["Productivity"],
    grade_bands: ["9-12"],
    audiences: ["Teachers", "Curriculum Leaders", "Administrators"],
    pricing_type: "Paid",
    pricing_details: "Plus at $10/mo. AI add-on at $8/mo. Education discounts available.",
    privacy_level: "Medium", accessibility_level: "Moderate",
    scores: { ease_of_use: 8, instructional_value: 9, data_privacy: 7, accessibility: 7 },
    overall_score: 8.2,
    tags: ["productivity", "organization", "planning", "AI writing", "workspace"],
    integrations: ["Google Drive", "Slack", "GitHub"],
    compliance_signals: [{ label: "SOC 2 Type II", status: "available", url: "https://www.magicschool.ai/privacy" }],
    last_reviewed: "2026-03-22", reviewer_notes: "Excellent for organized educators. Not a classroom tool.",
        vpat_status: "not_available" as const, vpat_url: null, vpat_notes: "No public VPAT/ACR found. Contact Notion for accessibility documentation.",
listing_tier: "basic", is_featured: false, featured_rank: null, is_sponsored: false, status: "published",
    similar_tools: [],
  },
];

// Merge original 25 tools with 39 new tools
const allRawTools = [
  ...rawTools,
  ...newTools.map((t, i) => ({ ...t, id: String(26 + i) })),
];

export const tools: Tool[] = allRawTools.map((t) => ({
  ...t,
  privacy_flag: derivePrivacyFlag(t.privacy_level),
}));

export const savedViews: SavedView[] = [
  { id: "all", label: "All Tools", filters: {} },
  { id: "district-ready", label: "District Ready", filters: { privacy_flag: "District Ready" } },
  { id: "free", label: "Free Tools", filters: { pricing: "Free" } },
  { id: "top-rated", label: "Top Rated (8.5+)", filters: { min_score: 8.5 } },
  { id: "teacher-tools", label: "Teacher Tools", filters: {} },
];

export function getToolBySlug(slug: string): Tool | undefined {
  return tools.find((t) => t.slug === slug);
}

export function getToolById(id: string): Tool | undefined {
  return tools.find((t) => t.id === id);
}

export function getToolsByIds(ids: string[]): Tool[] {
  return ids.map((id) => tools.find((t) => t.id === id || t.slug === id)).filter(Boolean) as Tool[];
}

export function getSimilarTools(tool: Tool): Tool[] {
  return tool.similar_tools.map((slug) => tools.find((t) => t.slug === slug)).filter(Boolean) as Tool[];
}

// Top Tools This Month — weighted by overall score + recency
export function getTopToolsThisMonth(count = 10): Tool[] {
  return [...tools]
    .sort((a, b) => {
      const scoreWeight = 0.7;
      const recencyWeight = 0.3;
      const aRecency = new Date(a.last_reviewed).getTime();
      const bRecency = new Date(b.last_reviewed).getTime();
      const maxRecency = Math.max(...tools.map((t) => new Date(t.last_reviewed).getTime()));
      const minRecency = Math.min(...tools.map((t) => new Date(t.last_reviewed).getTime()));
      const range = maxRecency - minRecency || 1;
      const aNorm = (aRecency - minRecency) / range;
      const bNorm = (bRecency - minRecency) / range;
      const aFinal = a.overall_score * scoreWeight + aNorm * 10 * recencyWeight;
      const bFinal = b.overall_score * scoreWeight + bNorm * 10 * recencyWeight;
      return bFinal - aFinal;
    })
    .slice(0, count);
}

// Best Free Tools — free or freemium, sorted by overall score
export function getBestFreeTools(count = 10): Tool[] {
  return [...tools]
    .filter((t) => t.pricing_type === "Free" || t.pricing_type === "Freemium")
    .sort((a, b) => b.overall_score - a.overall_score)
    .slice(0, count);
}

// Featured tools — those marked as featured, sorted by featured_rank
export function getFeaturedTools(): Tool[] {
  return [...tools]
    .filter((t) => t.is_featured && t.featured_rank !== null)
    .sort((a, b) => (a.featured_rank ?? 99) - (b.featured_rank ?? 99));
}
